const element=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
const field=(title,input)=>{const label=element('label',title,{class:'ad-api-field'});label.append(input);return label;};
const download=(data)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=element('a');a.href=url;a.download='剧情绘图_API配置.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export function mountApiPanel({host,app,setting,saveSettings=()=>{}}){
    const panel=element('section',undefined,{class:'ad-api-panel','aria-label':'剧情绘图 API 配置'}),status=element('p','',{role:'status','aria-live':'polite',class:'ad-api-status'});
    let selectedId='',models=[],busy=false,epoch=0;
    const action=(text,fn,{freeze=false}={})=>{const b=element('button',text,{type:'button','aria-label':text});b.onclick=async()=>{if(busy)return;const turn=++epoch;busy=true;panel.setAttribute('aria-busy','true');const controls=freeze?[...panel.querySelectorAll('input:not([type=file]),textarea,select')].map(input=>[input,input.disabled]):[];for(const[input]of controls)input.disabled=true;for(const button of panel.querySelectorAll('button'))button.disabled=true;status.textContent='';status.setAttribute('role','status');try{await fn(turn);}catch(error){if(turn===epoch){status.textContent=error.message;status.setAttribute('role','alert');}}finally{if(turn===epoch){busy=false;panel.setAttribute('aria-busy','false');for(const[input,disabled]of controls)input.disabled=disabled;for(const button of panel.querySelectorAll('button'))button.disabled=false;}}};return b;};
    const profileSelect=element('select',undefined,{'aria-label':'LLM 配置'}),name=element('input',undefined,{type:'text','aria-label':'配置名称',maxlength:'80'});
    const url=element('textarea',undefined,{rows:'2','aria-label':'API Base URL',placeholder:'https://api.example.com/v1',spellcheck:'false'});
    const key=element('input',undefined,{type:'password','aria-label':'API Key',autocomplete:'off',spellcheck:'false'}),visibility=action('显示密钥',()=>{key.type=key.type==='password'?'text':'password';visibility.textContent=key.type==='password'?'显示密钥':'隐藏密钥';visibility.setAttribute('aria-label',visibility.textContent);});
    const modelSelect=element('select',undefined,{'aria-label':'模型列表'}),model=element('input',undefined,{type:'text','aria-label':'模型名称',placeholder:'可选择或手动填写模型',spellcheck:'false'});
    const bypass=element('input',undefined,{type:'checkbox','aria-label':'直接连接 API'}),timeout=element('input',undefined,{type:'number',min:'10',max:'300','aria-label':'请求超时（秒）'});
    const includeKey=element('input',undefined,{type:'checkbox','aria-label':'导出包含密钥'}),headersEnabled=element('input',undefined,{type:'checkbox','aria-label':'启用自定义请求头'}),headers=element('textarea',undefined,{rows:'3','aria-label':'自定义请求头',placeholder:'Header-Name: value',spellcheck:'false'});
    const transport=element('select',undefined,{'aria-label':'选段连接方式'});transport.append(element('option','使用本插件 API 配置',{value:'plugin'}),element('option','使用电脑助手（兼容旧版）',{value:'helper'}));transport.value=setting().manual_transport==='helper'?'helper':'plugin';
    const helper=element('input',undefined,{type:'url','aria-label':'电脑助手地址',placeholder:'http://电脑局域网地址:8189'});helper.value=setting().manual_helper_url||'';
    const draft=()=>({id:selectedId||undefined,name:name.value,api_url:url.value,api_key:key.value,model:model.value,bypass_proxy:bypass.checked,timeout_seconds:Number(timeout.value),models,enable_custom_headers:headersEnabled.checked,custom_headers:headers.value});
    function showModels(){modelSelect.replaceChildren(element('option','选择模型（也可手动填写）',{value:''}),...models.map(m=>element('option',m,{value:m})));modelSelect.value=models.includes(model.value)?model.value:'';}
    function load(record){selectedId=record?.id||'';name.value=record?.name||'新配置';url.value=record?.api_url||'';key.value=record?.api_key||'';key.type='password';visibility.textContent='显示密钥';visibility.setAttribute('aria-label','显示密钥');model.value=record?.model||'';bypass.checked=record?.bypass_proxy===true;timeout.value=String(record?.timeout_seconds||60);headersEnabled.checked=record?.enable_custom_headers===true;headers.value=record?.custom_headers||'';models=[...(record?.models||[])];showModels();headers.disabled=!headersEnabled.checked;}
    function refresh(preferredId){const profiles=app.listApiProfiles();profileSelect.replaceChildren(...profiles.map(p=>element('option',p.name+(p.active?'（当前使用）':''),{value:p.id})));const current=profiles.find(p=>p.id===preferredId)||profiles.find(p=>p.active)||profiles[0];profileSelect.value=current?.id||'';load(current);}
    profileSelect.onchange=()=>{if(busy)return;const record=app.useApiProfile(profileSelect.value);transport.value='plugin';load(record);status.textContent='已切换为 '+record.name+'。此配置用于后续选段整理。';};
    modelSelect.onchange=()=>{if(modelSelect.value)model.value=modelSelect.value;};model.oninput=()=>{modelSelect.value=models.includes(model.value)?model.value:'';};headersEnabled.onchange=()=>{headers.disabled=!headersEnabled.checked;};
    const toolbar=element('div',undefined,{class:'ad-api-toolbar'}),actions=element('div',undefined,{class:'ad-api-actions'}),file=element('input',undefined,{type:'file',accept:'.json,application/json',hidden:'','aria-label':'导入 API 配置文件'});
    const persist=()=>{const saved=app.saveApiProfile(draft());transport.value='plugin';setting().manual_transport='plugin';setting().manual_helper_url=helper.value.trim();saveSettings();refresh(saved.id);status.textContent='API 配置已保存，后续选段立即使用。';return saved;};
    toolbar.append(field('LLM 配置',profileSelect),action('新增配置',()=>{load();name.focus();status.textContent='填写新配置后点击保存。';}),action('保存配置',persist),action('重命名配置',()=>{name.focus();name.select();status.textContent='修改配置名称后点击保存。';}),action('导入配置',()=>file.click()),action('导出配置',()=>{download(app.exportApiProfiles({includeKey:includeKey.checked}));status.textContent=includeKey.checked?'已导出包含密钥的配置。':'已导出配置，密钥和自定义请求头未包含。';}),action('删除配置',()=>{if(!selectedId)throw new Error('当前新配置尚未保存。');app.deleteApiProfile(selectedId);refresh();status.textContent='已删除所选 API 配置。';}));
    const keyRow=element('div',undefined,{class:'ad-api-key'});keyRow.append(key,visibility);const modelRow=element('div',undefined,{class:'ad-api-model'});modelRow.append(modelSelect,model);
    actions.append(action('连接并获取模型',async turn=>{status.textContent='正在获取模型列表…';const found=await app.fetchApiModels(draft());if(turn!==epoch)return;models=found;showModels();status.textContent='已获取 '+found.length+' 个模型；当前填写的模型保留。选择后点击保存。';},{freeze:true}),action('测试模型',async turn=>{status.textContent='正在用当前填写的模型测试连接…';const result=await app.testApiProfile(draft());if(turn===epoch)status.textContent='模型测试成功：'+result.model+'。这次测试未保存修改。';},{freeze:true}));
    const advanced=element('details');advanced.append(element('summary','高级与导入导出'),field('直接连接 API（默认使用酒馆代理）',bypass),field('请求超时（秒）',timeout),field('启用自定义请求头',headersEnabled),field('自定义请求头',headers),field('导出包含密钥',includeKey),field('选段连接方式',transport),field('电脑助手地址（兼容旧版）',helper));
    transport.onchange=()=>{setting().manual_transport=transport.value;setting().manual_helper_url=helper.value.trim();saveSettings();};helper.onchange=()=>{setting().manual_helper_url=helper.value.trim();saveSettings();};
    file.onchange=async()=>{try{if(!file.files[0])return;const added=app.importApiProfiles(JSON.parse(await file.files[0].text()));refresh();status.textContent='已导入 '+added.length+' 套配置，当前使用配置保持不变。';}catch(error){status.textContent='导入失败：'+error.message;status.setAttribute('role','alert');}finally{file.value='';}};
    panel.append(element('h3','API 配置'),element('p','用于选段整理与标签生成。自动插图标记由主对话产生，图片由 ComfyUI 绘制。',{class:'ad-library-muted'}),toolbar,field('配置名称',name),field('API Base URL（请包含服务要求的 /v1 等后缀）',url),field('API Key',keyRow),field('模型选择',modelRow),actions,status,advanced,file);
    host.append(panel);refresh();return {refresh,panel,destroy(){epoch++;panel.remove();}};
}
