const e=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};
export function mountComfyPanel({host,app,notify}){
    const section=e('section',undefined,{class:'ad-api-card',role:'region','aria-label':'ComfyUI 配置'}),grid=e('div',undefined,{class:'ad-comfy-grid'}),fields={},status=e('p','',{role:'status'});
    for(const[key,label,type]of[['url','ComfyUI 地址','url'],['MODEL_NAME','模型文件名','text'],['comfyuiCLIPName','CLIP 文件名','text'],['comfyui_vae','VAE 文件名','text'],['comfyui_steps','步数','number'],['cfg_comfyui','CFG','number'],['comfyui_width','宽度','number'],['comfyui_height','高度','number'],['comfyuisamplerName','采样器','text'],['comfyui_scheduler','调度器','text'],['UCP_comfyui','额外负面提示词','textarea'],['AQT_comfyui','额外正面提示词','textarea']]){
        const input=e(type==='textarea'?'textarea':'input',undefined,{...type==='textarea'?{rows:'3'}:{type},'aria-label':label});if(type==='number'){input.step=key==='cfg_comfyui'?'.1':'1';input.min=key==='cfg_comfyui'?'0':key==='comfyui_steps'?'1':'64';input.max=key==='cfg_comfyui'?'30':key==='comfyui_steps'?'200':'16384';}fields[key]=input;const labelNode=e('label',undefined,{class:'ad-library-field'});labelNode.append(e('span',label),input);grid.append(labelNode);
    }
    const action=(text,fn)=>{const button=e('button',text,{type:'button'});button.onclick=async()=>{button.disabled=true;try{await fn();}catch(error){status.textContent=error.message;notify(error.message,'error');}finally{button.disabled=false;}};return button;};
    const load=()=>{const values=app.getRenderSettings();for(const[key,input]of Object.entries(fields))input.value=values[key]??'';};
    section.append(e('h3','ComfyUI 配置'),e('p','手机填写绘图电脑的局域网地址。工作流使用 %prompt%、%negative_prompt%、%seed%、%width% 等占位符；固定写在工作流节点里的参数以节点为准。',{class:'ad-library-muted'}),grid,status,action('保存绘图设置',()=>{app.saveRenderSettings(Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,v.value])));load();status.textContent='绘图设置已保存，下一张图片开始使用。';}),action('测试 ComfyUI 连接',async()=>{const result=(await app.checkConnections()).find(r=>r.kind==='render');status.textContent=result.text;}));host.append(section);load();return {refresh:load,destroy:()=>section.remove()};
}
