import {MAIN_PROFILES,DEFAULT_MAIN_PROFILE} from './model-profiles.mjs';
import {usesPrototypeTrigger,usesImageReference} from './identity.mjs';
import {applyOutfit} from './wardrobe-state.mjs';
import {mountCatalogPane,mountArtistPane} from './preference-panels.mjs';
import {appearanceSummary} from './narrative-appearance.mjs';
import {mountApiPanel} from './api-panel.mjs';
import {mountCachePanel} from './cache-panel.mjs';
import {mountComfyPanel} from './comfy-panel.mjs';
import {mountWorldbookPanel} from './worldbook-panel.mjs';
import {manualInstruction} from './manual-instruction.mjs';
const e=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};
const split=value=>String(value||'').split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
const field=(title,input)=>{const l=e('div',undefined,{class:'ad-library-field'});l.append(e('span',title),input);return l;};
const fileData=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(f);});
const STATES={worn:'穿好',removed:'已脱下',open:'敞开',partly_open:'部分敞开',rolled:'卷起',loose:'松开',held:'拿着',draped:'搭着'};
const STYLES={model_default:'模型原生画风',painterly:'细腻插画',mikko:'柔和动画',bluearchive:'清透动画',rdbt:'复古日漫',pc98:'PC98'};
const download=(data,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=e('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function checkGraph(value){if(!value||typeof value!=='object'||Array.isArray(value)||!Object.keys(value).length)throw new Error('请填写 ComfyUI 导出的 API 格式工作流。');if(Array.isArray(value.nodes))throw new Error('这是画布工作流，请从 ComfyUI 导出 API 格式再导入。');for(const[id,node]of Object.entries(value)){if(!node||typeof node.class_type!=='string'||!node.inputs||typeof node.inputs!=='object'||Array.isArray(node.inputs))throw new Error('节点 '+id+' 缺少 class_type 或 inputs。');for(const input of Object.values(node.inputs))if(Array.isArray(input)&&input.length===2&&typeof input[1]==='number'&&!value[String(input[0])])throw new Error('节点 '+id+' 引用了不存在的节点 '+input[0]+'。');}return value;}

export function mountLibraryPanel({app,setting,notify,configure,installBook,worldbooks,saveSettings=()=>{}}){
    const host=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings')||document.body;
    const section=e('section',undefined,{class:'ad-library','aria-label':'剧情绘图插件'}),details=e('details'),summary=e('summary','剧情绘图 · 人物与衣装'),body=e('div',undefined,{class:'ad-library-body'});
    let tabId='people',epoch=0,workflowId='',dirty=false,records=[],catalogUi,artistUi;
    const button=(text,fn,attrs={})=>{const b=e('button',text,{type:'button','aria-label':text,...attrs});b.onclick=async()=>{b.disabled=true;try{await fn();}catch(error){notify(error.message,'error');}finally{b.disabled=false;}};return b;};
    const api=name=>{if(typeof app[name]!=='function')throw new Error('此功能尚未连接，请重新加载更新后的剧情绘图插件。');return app[name].bind(app);};
    const toggle=(text,input)=>{const l=e('label',undefined,{class:'ad-library-toggle'});l.append(input,e('span',text));return l;};
    const enable=e('input',undefined,{type:'checkbox','aria-label':'启用剧情绘图'}),auto=e('input',undefined,{type:'checkbox','aria-label':'随回复准备自动插图按钮'});enable.checked=setting().enabled!==false;auto.checked=setting().automatic!==false;enable.onchange=()=>{setting().enabled=enable.checked;app.anchors();saveSettings();};auto.onchange=()=>{setting().automatic=auto.checked;app.anchors();saveSettings();};
    const switches=e('div',undefined,{class:'ad-library-switches'});switches.append(toggle('启用剧情绘图',enable),toggle('随回复准备自动插图按钮',auto));
    const renderAuto=e('input',undefined,{type:'checkbox','aria-label':'新回复完成后自动生成图片'}),maxAuto=e('select',undefined,{'aria-label':'每条自动生成数量'});renderAuto.checked=setting().automatic_render===true;for(let i=1;i<=3;i++)maxAuto.append(e('option',String(i)+' 张',{value:String(i)}));maxAuto.value=String(setting().automatic_max_images||1);renderAuto.onchange=()=>{setting().automatic_render=renderAuto.checked;if(!renderAuto.checked)app.stopQueued?.();saveSettings();};maxAuto.onchange=()=>{setting().automatic_max_images=Number(maxAuto.value);saveSettings();};switches.append(toggle('新回复完成后自动生成图片',renderAuto),field('每条自动生成数量',maxAuto));
    const tasks=e('details',undefined,{class:'ad-generation-status'}),taskStatus=e('p','等待新的回复',{role:'status','aria-live':'polite'}),taskList=e('div',undefined,{class:'ad-generation-tasks'}),taskActions=e('div',undefined,{class:'ad-library-actions'}),health=e('div',undefined,{class:'ad-generation-health'});
    tasks.open=true;tasks.append(e('summary','自动插图与任务状态'),taskStatus,e('p','只自动绘制更新后收到的新回复，默认每条一张、逐张生成；其它按钮仍可手动使用。失败会暂停后续任务，停止待生成任务不会中断已提交的 GPU 任务。',{class:'ad-library-muted'}),taskActions,health,taskList);
    taskActions.append(button('检查绘图连接',async()=>{health.textContent='正在检查 ComfyUI；选段接口只核对配置…';const results=await api('checkConnections')();health.replaceChildren(...results.map(r=>e('p',(r.ok?'✓ ':'! ')+r.text,{class:r.ok?'':'ad-error'})));}),button('停止待生成任务',()=>app.stopQueued?.()),button('继续队列',()=>app.resumeQueue?.()));
    const taskLabels={queued:'排队',generating:'生成中',complete:'已保存',failed:'失败',cancelled:'已停止'};
    function renderTasks(){if(typeof app.getGenerationStatus!=='function'){tasks.hidden=true;return;}const status=app.getGenerationStatus();taskStatus.textContent=status.automatic.reason+(status.paused?' · 队列已暂停':'');taskList.replaceChildren();for(const row of status.tasks.slice(-8).reverse()){const card=e('article',undefined,{class:'ad-generation-task'});card.dataset.status=row.status;card.append(e('strong',(taskLabels[row.status]||row.status)+' · 第 '+(row.message_id+1)+' 条消息'),e('p',row.summary),e('p',row.reason||''));if(row.status==='failed')card.append(button('重试这张图片',()=>app.retryTask(row.id)));if(row.saved_asset_id)card.append(button('下载已保存结果',async()=>{const asset=await app.library.getAsset(row.saved_asset_id);if(!asset)throw new Error('图片记录不存在。');const a=e('a');a.href=asset.data;a.download='剧情插图.png';a.click();}));taskList.append(card);}}
    const backend=e('select',undefined,{'aria-label':'ComfyUI 后端类型'});backend.append(e('option','标准 ComfyUI（单机）',{value:'standard'}),e('option','安装了 MGPU 扩展',{value:'mgpu'}));backend.value=setting().standard_comfy_history===false?'mgpu':'standard';backend.onchange=()=>{setting().standard_comfy_history=backend.value==='standard';saveSettings();};
    const generationUpdated=()=>renderTasks();window.addEventListener('animadex-tasks-updated',generationUpdated);renderTasks();
    const count=e('p','读取当前聊天的人物与衣装…',{class:'ad-library-count',role:'status'}),nav=e('nav',undefined,{class:'ad-library-tabs','aria-label':'剧情绘图管理'}),panes={},tabs={};
    for(const[id,label]of[['people','人物'],['catalog','角色库'],['outfits','衣装'],['artists','画风'],['workflows','工作流'],['api','API 配置'],['comfy','ComfyUI'],['cache','图片缓存'],['worldbooks','世界书']]){panes[id]=e('div',undefined,{class:'ad-library-pane',hidden:''});panes[id].dataset.pane=id;tabs[id]=button(label,async()=>{setTab(id);if(id==='workflows')await renderWorkflows();if(id==='catalog')await catalogUi.refresh();if(id==='artists')artistUi.refresh();if(id==='comfy')comfyUi.refresh();if(id==='cache')await cacheUi.refresh();if(id==='worldbooks')await worldbookUi.refresh();},{'aria-pressed':'false'});nav.append(tabs[id]);}
    const worldbookUi=mountWorldbookPanel({host:panes.worldbooks,store:worldbooks,notify,preview:scope=>scope==='manual'?manualInstruction(setting()):app.anchors()});const apiUi=mountApiPanel({host:panes.api,app,setting,saveSettings});const comfyUi=mountComfyPanel({host:panes.comfy,app,notify}),cacheUi=mountCachePanel({host:panes.cache,app,notify});
    function setTab(id){tabId=id;for(const key of Object.keys(panes)){panes[key].hidden=key!==id;tabs[key].setAttribute('aria-pressed',String(key===id));}}
    const file=e('input',undefined,{type:'file',accept:'.json,application/json',hidden:'','aria-label':'导入人物与衣装备份'});file.onchange=async()=>{try{if(!file.files[0])return;await app.importLibrary(JSON.parse(await file.files[0].text()));await render();notify('人物库备份已导入。');}catch(error){notify(error.message,'error');}finally{file.value='';}};
    const utilities=e('details',undefined,{class:'ad-library-utilities'}),utilitiesActions=e('div',undefined,{class:'ad-library-actions'});utilitiesActions.append(button('导出人物与衣装备份',async()=>download(await app.exportLibrary(),'剧情绘图人物库.json')),button('导入备份',()=>file.click()),button('管理生图世界书',async()=>{setTab('worldbooks');await worldbookUi.refresh();}),button('配置绘图工作流',async()=>{await configure();await renderWorkflows(true);}));utilities.append(e('summary','备份与世界书'),utilitiesActions,file);
    const search=e('input',undefined,{type:'search','aria-label':'查找人物',placeholder:'查找人物、识别词或发型'}),gallery=e('div',undefined,{class:'ad-person-gallery'}),peopleHeading=e('div',undefined,{class:'ad-library-pane-heading'});peopleHeading.append(e('h3','当前聊天的人物'),search);panes.people.append(peopleHeading,gallery);search.oninput=()=>renderPeople(app.getStory(),++epoch);
    const personFilter=e('select',undefined,{'aria-label':'衣装人物筛选'}),messageFilter=e('select',undefined,{'aria-label':'衣装回复筛选'}),outfitList=e('div',undefined,{class:'ad-outfit-timeline'}),outfitCount=e('p','',{class:'ad-library-muted'}),filters=e('div',undefined,{class:'ad-outfit-filters'});filters.append(field('人物',personFilter),field('回复',messageFilter));panes.outfits.append(e('h3','衣装变化'),e('p','按剧情时刻查看穿着。相同衣物的穿脱、敞开和卷袖分别记录。',{class:'ad-library-muted'}),filters,outfitCount,outfitList);personFilter.onchange=messageFilter.onchange=()=>renderOutfits(app.getStory());
    async function previewFor(p,story){const ids=[...(p.reference_ids||[]),p.saved_from];for(const scene of Object.values(story.scenes||{}).reverse())if(scene.actors?.some(a=>a.person===p.person))ids.push(scene.selected_image,...(scene.images||[]).slice().reverse());for(const id of new Set(ids.filter(Boolean))){const asset=await app.library.getAsset(id);if(asset?.data)return asset;}return null;}
    async function renderPeople(story,turn){if(!story)return;const query=search.value.trim().toLowerCase(),cast=Object.values(story.cast.people),shown=cast.filter(p=>[p.person,p.prototype_trigger,...(p.aliases||[]),...(p.chosen_appearance_tags||[])].join(' ').toLowerCase().includes(query));const rows=await Promise.all(shown.map(async p=>{const row=e('article',undefined,{class:'ad-person-card'}),portrait=e('div',undefined,{class:'ad-person-portrait'}),asset=await previewFor(p,story);if(asset)portrait.append(e('img',undefined,{src:asset.data,alt:p.person+' 的本地形象',loading:'lazy'}));else portrait.append(e('span','暂无图片'),e('small','出图满意后双击保存形象'));const info=e('div',undefined,{class:'ad-person-card-info'}),hair=(p.chosen_appearance_tags||[]).filter(t=>/hair|bangs|braid|ponytail|髮|发/.test(t)),actions=e('div',undefined,{class:'ad-person-card-actions'});info.append(e('h3',p.person),e('span',p.accepted?'已保存形象':'暂用形象',{class:'ad-person-badge'+(p.accepted?' is-saved':'')}),e('p',p.prototype_trigger||'按剧情固定外貌 · 尚未匹配原型',{class:'ad-person-trigger'}),e('p',hair.join(', ')||'发型尚未记录',{class:'ad-person-hair'}));actions.append(button('管理形象与画风',()=>editPerson(p)),button('查看衣装变化',()=>{personFilter.value=p.person;messageFilter.value='';setTab('outfits');renderOutfits(app.getStory());}));info.append(actions);row.append(portrait,info);return row;}));if(turn!==epoch)return;gallery.replaceChildren(...rows);if(!rows.length)gallery.append(e('p',cast.length?'没有找到这个人物。试试姓名、识别词或发型。':'新人物出图后会在这里显示。双击满意图片可保存固定形象。',{class:'ad-library-empty'}));}
    async function editPerson(p){
        const d=e('dialog',undefined,{class:'ad-manual ad-profile','aria-label':'人物档案'}),header=e('header'),body=e('div',undefined,{class:'ad-manual-body'});header.append(e('h2',p.person+' 的固定形象'));
        const hero=e('div',undefined,{class:'ad-profile-hero'}),asset=await previewFor(p,app.getStory());if(asset)hero.append(e('img',undefined,{src:asset.data,alt:p.person+' 的固定形象'}));const heroText=e('div');heroText.append(e('strong',p.person),e('p',p.accepted?'已保存。后续新图复用这一形象。':'暂用形象。满意图片可双击保存。'),e('p','旧图片保留当时的人物与衣装。'),e('p',appearanceSummary(p),{class:'ad-appearance-contract','aria-label':'人物外貌分类'}));hero.append(heroText);
        const tags=e('textarea',undefined,{'aria-label':'固定外貌 tags',rows:'5',spellcheck:'false'}),age=e('input',undefined,{type:'text',maxlength:'120','aria-label':'固定年龄'}),face=e('textarea',undefined,{rows:'3',maxlength:'700','aria-label':'固定脸部描述'});tags.value=(p.chosen_appearance_tags||[]).join(', ');age.value=p.age_description||'';face.value=p.face_description||'';
        const aliases=e('input',undefined,{type:'text','aria-label':'人物别名',placeholder:'多个名字用逗号分隔'}),prototype=e('input',undefined,{type:'text','aria-label':'原型识别词',spellcheck:'false'});aliases.value=(p.aliases||[]).join(', ');prototype.value=p.prototype_trigger||'';
        const trigger=e('input',undefined,{type:'checkbox','aria-label':'使用 Animadex 原型识别词'}),reference=e('input',undefined,{type:'checkbox','aria-label':'使用图片参考增强'});trigger.checked=usesPrototypeTrigger(p);reference.checked=usesImageReference(p);
        const style=e('select',undefined,{'aria-label':'人物画风'});for(const[id,label]of Object.entries(STYLES))style.append(e('option',label,{value:id}));style.value=p.style||'model_default';const artists=e('input',undefined,{type:'text','aria-label':'画师标签',placeholder:'例如 @画师名，多个用逗号分隔',spellcheck:'false'});artists.value=(p.artist_tags||[]).join(', ');
        const appearance=e('section',undefined,{class:'ad-profile-section'}),recognition=e('section',undefined,{class:'ad-profile-section'}),refsSection=e('section',undefined,{class:'ad-profile-section'});appearance.append(e('h3','固定外貌'),e('p','发型、发色与身体特征保存在这里。换衣服不会改动它们。',{class:'ad-library-muted'}),field('固定外貌 tags',tags),field('固定年龄',age),field('固定脸部描述',face));recognition.append(e('h3','名字与画风'),field('人物别名',aliases),field('原型识别词',prototype),toggle('使用 Animadex 原型识别词',trigger),field('人物画风',style),field('画师标签',artists));
        const refs=e('div',undefined,{class:'ad-profile-references'});for(const id of p.reference_ids||[]){const ref=await app.library.getAsset(id);if(!ref)continue;const wrapper=e('figure');wrapper.append(e('img',undefined,{src:ref.data,alt:p.person+' 的形象参考'}),button('移除此参考',async()=>{await app.updatePerson(p.person,{removeReference:id});wrapper.remove();await render();}));refs.append(wrapper);}
        const input=e('input',undefined,{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'添加脸部或其它角度参考'});refsSection.append(e('h3','参考图片'),toggle('使用图片参考增强（较慢，可选）',reference),refs,field('添加脸部或其它角度参考',input));
        const grid=e('div',undefined,{class:'ad-profile-grid'});grid.append(appearance,recognition);body.append(hero,grid,refsSection);const footer=e('footer');footer.append(button('取消',()=>d.close()),button('保存人物档案',async()=>{const referenceData=input.files[0]?await fileData(input.files[0]):undefined;await app.updatePerson(p.person,{tags:split(tags.value),style:style.value,age_description:age.value,face_description:face.value,trigger_enabled:trigger.checked,reference_enabled:reference.checked,referenceData,prototype_trigger:prototype.value,aliases:split(aliases.value),artist_tags:split(artists.value)});d.close();await render();notify(p.person+' 的人物档案已保存。');},{class:'ad-primary'}));d.append(header,body,footer);document.body.append(d);d.onclose=()=>d.remove();d.showModal();
    }
    function outfitRows(story){const rows=[],previous=new Map();for(const[id,event]of Object.entries(typeof app.getOutfitEvents==='function'?app.getOutfitEvents():story.events||{}).sort(([,a],[,b])=>a.message_id-b.message_id||a.offset-b.offset)){for(const actor of event.people||[]){let current;try{current=applyOutfit(previous.get(actor.name),actor.outfit);}catch(error){rows.push({id,event,actor,error:error.message});continue;}const before=previous.get(actor.name),changed=current.items.filter(item=>JSON.stringify(before?.items?.find(x=>x.id===item.id))!==JSON.stringify(item));rows.push({id,event,actor,current,before,changed});previous.set(actor.name,current);}}return rows;}
    function renderOutfits(story){if(!story)return;const rows=outfitRows(story).filter(r=>(!personFilter.value||r.actor.name===personFilter.value)&&(!messageFilter.value||String(r.event.message_id)===messageFilter.value));outfitCount.textContent=rows.length+' 条穿着记录';outfitList.replaceChildren();for(const r of rows){const card=e('article',undefined,{class:'ad-outfit-event'}),head=e('div',undefined,{class:'ad-outfit-event-head'});head.append(e('strong',r.actor.name),e('span','第 '+(r.event.message_id+1)+' 条回复'),e('span',r.id.includes(':memory:')?'无插图段落':'插图时刻',{class:'ad-outfit-kind'}));card.append(head);if(r.error)card.append(e('p',r.error,{role:'alert'}));else{const items=e('div',undefined,{class:'ad-outfit-items'});for(const item of r.current.items){const chip=e('span',undefined,{class:'ad-outfit-chip'+(item.state==='removed'?' is-removed':'')});chip.append(e('strong',item.name||item.id),e('span',STATES[item.state]||item.state));items.append(chip);}card.append(items);if(!r.current.items.length)card.append(e('p','这一个时刻没有记录衣物。',{class:'ad-library-muted'}));card.append(e('p',r.changed.length?'变化：'+r.changed.map(item=>{const old=r.before?.items?.find(x=>x.id===item.id);return(item.name||item.id)+' '+(old?STATES[old.state]+' → ':'')+STATES[item.state];}).join('；'):'沿用上一个时刻的穿着。',{class:'ad-outfit-change'}),button('编辑此时衣装',()=>editOutfit(r)));}outfitList.append(card);}if(!rows.length)outfitList.append(e('p','当前筛选下没有衣装记录。',{class:'ad-library-empty'}));}
    function editOutfit(row){
        const d=e('dialog',undefined,{class:'ad-manual ad-outfit-editor','aria-label':'编辑此时衣装'}),header=e('header'),body=e('div',undefined,{class:'ad-manual-body'}),list=e('div',undefined,{class:'ad-outfit-editor-list'}),draft=structuredClone(row.current.items);header.append(e('h2',row.actor.name+' · 第 '+(row.event.message_id+1)+' 条回复'));body.append(e('p','修改这个剧情时刻的完整穿着。已经生成的图片保留原来的衣装快照。'),list);
        function renderItems(){list.replaceChildren();draft.forEach((item,index)=>{const box=e('section',undefined,{class:'ad-outfit-editor-item'}),name=e('input',undefined,{type:'text','aria-label':'衣物名称 '+(index+1)}),tags=e('textarea',undefined,{rows:'2','aria-label':'款式 tags '+(index+1)}),state=e('select',undefined,{'aria-label':'穿着状态 '+(index+1)}),stateTags=e('input',undefined,{type:'text','aria-label':'状态 tags '+(index+1)}),condition=e('input',undefined,{type:'text','aria-label':'衣物状况 tags '+(index+1)});name.value=item.name||item.id;tags.value=(item.tags||[]).join(', ');stateTags.value=(item.state_tags||[]).join(', ');condition.value=(item.condition_tags||[]).join(', ');for(const[value,label]of Object.entries(STATES))state.append(e('option',label,{value}));state.value=item.state;name.oninput=()=>item.name=name.value;tags.oninput=()=>item.tags=split(tags.value);stateTags.oninput=()=>item.state_tags=split(stateTags.value);condition.oninput=()=>item.condition_tags=split(condition.value);state.onchange=()=>item.state=state.value;const head=e('div',undefined,{class:'ad-outfit-editor-heading'});head.append(e('strong','衣物 '+(index+1)),button('移除这条衣物',()=>{draft.splice(index,1);renderItems();},{class:'ad-danger'}));const grid=e('div',undefined,{class:'ad-outfit-editor-grid'});grid.append(field('衣物名称',name),field('穿着状态',state));box.append(head,grid,field('款式 tags',tags),field('状态 tags',stateTags),field('衣物状况 tags',condition));list.append(box);});}
        renderItems();body.append(button('添加衣物',()=>{draft.push({id:'item_'+crypto.randomUUID().replaceAll('-','').slice(0,12),name:'',state:'worn',tags:[],state_tags:[],condition_tags:[]});renderItems();}));const footer=e('footer');footer.append(button('取消',()=>d.close()),button('保存此时衣装',async()=>{applyOutfit(undefined,{mode:'snapshot',items:draft});await api('updateOutfit')({eventId:row.id,person:row.actor.name,items:draft});d.close();await render();notify('此时衣装已保存。');},{class:'ad-primary'}));d.append(header,body,footer);document.body.append(d);d.onclose=()=>d.remove();d.showModal();
    }
    const workflowSelect=e('select',undefined,{'aria-label':'工作流预设'}),workflowName=e('input',undefined,{type:'text','aria-label':'工作流名称',maxlength:'100',placeholder:'给这个工作流命名'}),json=e('textarea',undefined,{'aria-label':'工作流 JSON',rows:'14',spellcheck:'false',placeholder:'导入 ComfyUI API 工作流，或在这里粘贴 JSON。'}),workflowStatus=e('p','',{class:'ad-workflow-status',role:'status'}),workflowRow=e('div',undefined,{class:'ad-workflow-select-row'}),operations=e('details',undefined,{class:'ad-workflow-operations'}),actionGrid=e('div',undefined,{class:'ad-workflow-action-grid'});
    const main=e('select',undefined,{'aria-label':'主绘图模型'});for(const[id,p]of Object.entries(MAIN_PROFILES))main.append(e('option',p.label,{value:id}));main.value=setting().mainProfile||DEFAULT_MAIN_PROFILE;
    const modelHint=e('p','',{class:'ad-library-muted','aria-label':'绘图档位说明'}),updateHint=()=>{modelHint.textContent=MAIN_PROFILES[main.value]?.hint||'保留原来的模型参数与图片尺寸。';};main.onchange=updateHint;updateHint();
    const modelControls=e('div',undefined,{class:'ad-library-actions ad-main-model'});modelControls.append(main,button('应用主模型',async()=>{await configure(main.value);await renderWorkflows(true,true);notify('主绘图模型已应用。');}));
    function validate(){try{const graph=checkGraph(JSON.parse(json.value));workflowStatus.textContent=(dirty?'尚未保存 · ':'')+Object.keys(graph).length+' 个节点，JSON 与节点引用有效。';workflowStatus.classList.remove('is-error');return graph;}catch(error){workflowStatus.textContent=json.value.trim()?error.message:'导入 API 格式工作流后，可以查看和修改节点。';workflowStatus.classList.toggle('is-error',!!json.value.trim());return null;}}
    json.oninput=workflowName.oninput=()=>{dirty=true;validate();};
    async function renderWorkflows(force=false,followActive=false){if(typeof app.listWorkflows!=='function'){workflowStatus.textContent='工作流管理尚未连接，请重新加载更新后的插件。';return;}records=await app.listWorkflows();if(!Array.isArray(records))throw new Error('工作流列表格式不正确。');if(followActive||!(dirty&&!workflowId)&&!records.some(x=>x.id===workflowId))workflowId=records.find(x=>x.active)?.id||records[0]?.id||'';workflowSelect.replaceChildren();if(dirty&&!workflowId)workflowSelect.append(e('option','新工作流（尚未保存）',{value:''}));for(const record of records)workflowSelect.append(e('option',record.name+(record.active?'（当前使用）':''),{value:record.id}));if(!records.length)workflowSelect.append(e('option','尚无工作流预设',{value:''}));workflowSelect.value=workflowId;if(!dirty||force){dirty=false;const record=records.find(x=>x.id===workflowId);workflowName.value=record?.name||'';const graph=record?.workflow??(workflowId&&typeof app.getWorkflow==='function'?(await app.getWorkflow(workflowId))?.workflow:undefined);json.value=typeof graph==='string'?graph:graph?JSON.stringify(graph,null,2):'';validate();}}
    workflowSelect.onchange=async()=>{const requested=workflowSelect.value;if(dirty&&workflowId!==requested){workflowSelect.value=workflowId;const d=e('dialog',undefined,{class:'ad-manual','aria-label':'切换工作流'}),content=e('div',undefined,{class:'ad-manual-body'}),footer=e('footer');content.append(e('h2','放弃未保存的修改？'),e('p','这个工作流有未保存的修改。可以继续编辑，或放弃修改后切换。'));footer.append(button('继续编辑',()=>d.close()),button('放弃修改并切换',async()=>{dirty=false;workflowId=requested;await renderWorkflows(true);d.close();},{class:'ad-primary'}));d.append(content,footer);document.body.append(d);d.onclose=()=>d.remove();d.showModal();return;}workflowId=requested;try{await renderWorkflows(true);}catch(error){notify(error.message,'error');}};
    const workflowFile=e('input',undefined,{type:'file',accept:'.json,application/json',hidden:'','aria-label':'导入工作流 JSON'});workflowFile.onchange=async()=>{try{if(!workflowFile.files[0])return;const result=await api('importWorkflows')(JSON.parse(await workflowFile.files[0].text()));dirty=false;workflowId=result?.id||result?.workflows?.[0]?.id||'';await renderWorkflows(true);notify('工作流已导入。');}catch(error){notify(error.message,'error');}finally{workflowFile.value='';}};
    async function saveWorkflow(asNew=false){const graph=validate();if(!graph)throw new Error(workflowStatus.textContent);if(!workflowName.value.trim())throw new Error('请先填写工作流名称。');const result=await api('saveWorkflow')({id:asNew?undefined:workflowId||undefined,name:workflowName.value.trim(),workflow:graph,activate:false});workflowId=result.id;dirty=false;await renderWorkflows(true);notify('工作流已保存。');}
    async function removeWorkflow(){const record=records.find(x=>x.id===workflowId),d=e('dialog',undefined,{class:'ad-manual','aria-label':'删除工作流预设'}),content=e('div',undefined,{class:'ad-manual-body'}),footer=e('footer');content.append(e('h2','删除 '+(record?.name||'当前工作流')+'？'),e('p','删除前可以先导出备份。此操作只删除所选预设。'));footer.append(button('取消',()=>d.close()),button('删除预设',async()=>{await api('deleteWorkflow')(workflowId);workflowId='';dirty=false;await renderWorkflows(true);d.close();notify('工作流预设已删除。');},{class:'ad-danger'}));d.append(content,footer);document.body.append(d);d.onclose=()=>d.remove();d.showModal();}
    const actions=[['新建',()=>{workflowId='';dirty=true;workflowName.value='新工作流';json.value='{}';if(!workflowSelect.querySelector('option[value=""]'))workflowSelect.prepend(e('option','新工作流（尚未保存）',{value:''}));workflowSelect.value='';validate();workflowName.focus();}],['保存',()=>saveWorkflow()],['另存为',()=>{workflowId='';workflowName.value+=' 副本';dirty=true;return saveWorkflow(true);}],['重命名',()=>{if(!workflowId)throw new Error('请先选择已保存的工作流。');workflowName.focus();workflowName.select();workflowStatus.textContent='修改上方工作流名称后点击保存。';}],['导出当前',async()=>{if(!workflowId)throw new Error('请先保存这个工作流。');download(await api('exportWorkflows')({id:workflowId}),(workflowName.value||'工作流')+'.json');}],['导出全部',async()=>download(await api('exportWorkflows')({}),'剧情绘图工作流全部预设.json')],['导入',()=>workflowFile.click()],['删除预设',()=>{if(!workflowId)throw new Error('请先选择已保存的工作流。');return removeWorkflow();}]];
    for(const[label,fn]of actions)actionGrid.append(button(label,fn,{class:label==='删除预设'?'ad-danger':''}));operations.append(e('summary','工作流操作'),actionGrid);workflowRow.append(workflowSelect,operations);
    const use=button('使用此工作流',async()=>{if(dirty)throw new Error('请先保存修改，再使用此工作流。');if(!workflowId)throw new Error('请先选择或保存工作流。');await api('useWorkflow')(workflowId);await renderWorkflows(true);notify('当前绘图工作流已切换。');},{class:'ad-primary'});
    panes.workflows.append(e('h3','工作流'),e('p','选择模型或管理自己的 ComfyUI API 工作流。',{class:'ad-library-muted'}),modelControls,modelHint,field('工作流预设',workflowRow),field('工作流名称',workflowName),field('工作流（JSON）',json),workflowStatus,use,workflowFile);
    async function render(){const story=app.getStory();if(!story)return;const turn=++epoch,cast=Object.values(story.cast.people),person=personFilter.value,msg=messageFilter.value;count.textContent=cast.length+' 位人物 · '+Object.keys(story.scenes).length+' 个插图记录 · 独立本地存储';personFilter.replaceChildren(e('option','所有人物',{value:''}),...cast.map(p=>e('option',p.person,{value:p.person})));personFilter.value=cast.some(p=>p.person===person)?person:'';const ids=[...new Set(Object.values(typeof app.getOutfitEvents==='function'?app.getOutfitEvents():story.events||{}).map(x=>x.message_id))].sort((a,b)=>a-b);messageFilter.replaceChildren(e('option','所有回复',{value:''}),...ids.map(id=>e('option','第 '+(id+1)+' 条回复',{value:String(id)})));messageFilter.value=ids.some(id=>String(id)===msg)?msg:'';await renderPeople(story,turn);renderOutfits(story);if(tabId==='workflows')await renderWorkflows();if(tabId==='cache')await cacheUi.refresh();}
    catalogUi=mountCatalogPane({pane:panes.catalog,app,notify});artistUi=typeof app.getDrawingPreferences==='function'?mountArtistPane({pane:panes.artists,app,notify}):{refresh(){}};
    body.append(switches,tasks,count,nav,...Object.values(panes),utilities);details.append(summary,body);section.append(details);host.append(section);setTab('people');const updated=()=>render().catch(error=>notify(error.message,'error'));window.addEventListener('animadex-library-updated',updated);updated();return {render,section,setTab,destroy(){worldbookUi.destroy();apiUi.destroy();comfyUi.destroy();cacheUi.destroy();window.removeEventListener('animadex-library-updated',updated);window.removeEventListener('animadex-tasks-updated',generationUpdated);section.remove();}};
}
