import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {applyMainProfile,MAIN_PROFILES,DEFAULT_MAIN_PROFILE,WORKFLOW_VERSION,workflowUpgradeProfile,installWorkflowUpgrade}from './model-profiles.mjs';
const config=JSON.parse(fs.readFileSync(new URL('./workflow-config.json',import.meta.url))),workflow=JSON.parse(fs.readFileSync(new URL('./workflow-api.json',import.meta.url)));
test('Silvermoon clears inherited native quality negatives as well as preset negatives',()=>{const legacy={...structuredClone(config),settings:{...config.settings,UCP_comfyui:'legacy negative list'}};for(const id of['silvermoon','silvermoon_turbo']){const result=applyMainProfile(legacy,workflow,id);assert.equal(result.config.settings.UCP_comfyui,'');assert.equal(result.config.promptPreset.negativePrompt,'');}assert.equal(applyMainProfile(legacy,workflow,'harem').config.settings.UCP_comfyui,'legacy negative list');assert.equal(legacy.settings.UCP_comfyui,'legacy negative list');});
test('Silvermoon Turbo uses its native sampler and never stacks the old Turbo adapter',()=>{const before=structuredClone(workflow);const result=applyMainProfile(config,workflow,'silvermoon_turbo');assert.equal(result.workflow['19'].inputs.strength_model,0);assert.equal(result.workflow['30'].inputs.main_steps,10);assert.equal(result.workflow['30'].inputs.main_cfg,1);assert.equal(result.config.promptPreset.negativePrompt,'');assert.equal(result.workflow['15'].inputs.weight_dtype,'default');assert.equal(result.workflow['15'].inputs.unet_name,MAIN_PROFILES.silvermoon_turbo.model);assert.deepEqual(workflow,before);});
test('ordinary Silvermoon retains recommended sampling and the saved-reference adapter',()=>{for(const id of Object.keys(MAIN_PROFILES)){const result=applyMainProfile(config,workflow,id),standard=id==='silvermoon'||id==='silvermoon_quality'||id==='silvermoon_efficiency',optimized=id==='silvermoon_quality'||id==='silvermoon_efficiency';assert.equal(result.workflow['31'].inputs.unet_name,optimized?MAIN_PROFILES[id].model:standard?MAIN_PROFILES.silvermoon.model:'anima-base-v1.0.safetensors');assert.equal(result.workflow['30'].inputs.reference_cfg,standard?3:4);assert.equal(result.workflow['30'].inputs.reference_sampler,standard?'euler_ancestral':'er_sde');assert.equal(result.workflow['30'].inputs.reference_steps,id==='silvermoon_efficiency'?20:24);assert.equal(result.workflow['26'].inputs.reference_budget,id==='silvermoon_quality'?'quality':'standard');assert.deepEqual(result.workflow['29'],workflow['29']);}assert.throws(()=>applyMainProfile(config,workflow,'../../unknown'));});
test('tablet profiles are distinct presets with native INT8 and real higher generation resolution',()=>{
 const efficiency=applyMainProfile(config,workflow,'silvermoon_efficiency'),quality=applyMainProfile(config,workflow,'silvermoon_quality');
 assert.notEqual(efficiency.config.name,quality.config.name);assert.notEqual(quality.config.name,config.name);
 assert.equal(efficiency.config.settings.workerid,efficiency.config.name);assert.equal(quality.config.settings.workerid,quality.config.name);
 assert.deepEqual(efficiency.config.canvasBudget.portrait,[704,1152]);assert.deepEqual(quality.config.canvasBudget.portrait,[832,1344]);
 for(const p of[efficiency,quality]){assert.match(p.workflow['15'].inputs.unet_name,/INT8-ConvRot/);assert.equal(p.workflow['15'].inputs.weight_dtype,'default');assert.equal(p.workflow['26'].inputs.output_size,'tablet');assert.equal(p.workflow['19'].inputs.strength_model,0);assert.equal(p.workflow['23'].inputs.strength_model,0);assert.equal(p.config.promptPreset.fixedPrompt,'');assert.equal(p.config.promptPreset.negativePrompt,'');assert.equal(p.config.version,WORKFLOW_VERSION);}
 assert.equal(efficiency.workflow['30'].inputs.main_steps,24);assert.equal(quality.workflow['30'].inputs.main_steps,28);
 assert.deepEqual(quality.workflow['6'].inputs.width,['26',0]);assert.deepEqual(quality.workflow['12'].inputs.width,['26',2]);
});
test('one-time upgrade preserves custom workflows, artists, and later manual profile choices',async()=>{
 const calls=[],s={mainProfile:'silvermoon',default_artist_tags:['@my_artist']},native={workerid:'Animadex_剧情形象参考_v2',workers:{'Animadex_剧情形象参考_v2':'original graph'}};
 await installWorkflowUpgrade(s,native,async(id,options)=>calls.push({id,activate:options?.activate!==false}));
 assert.equal(calls.filter(c=>c.activate).length,1);assert.equal(calls.at(-1).id,DEFAULT_MAIN_PROFILE);assert.equal(native.workers[native.workerid],'original graph');assert.deepEqual(s.default_artist_tags,['@my_artist']);
 s.mainProfile='silvermoon_efficiency';await installWorkflowUpgrade(s,native,async()=>assert.fail('upgrade ran twice'));
 const custom={mainProfile:'silvermoon'},customNative={workerid:'我修改的工作流'};calls.length=0;
 await installWorkflowUpgrade(custom,customNative,async(id,options)=>calls.push({id,activate:options?.activate!==false}));assert.ok(calls.every(c=>!c.activate));assert.equal(custom.mainProfile,'silvermoon');assert.equal(customNative.workerid,'我修改的工作流');
 assert.equal(workflowUpgradeProfile({mainProfile:'harem'},{workerid:'Animadex_剧情形象参考_v2'}),'harem');
});
