import {prototypeCard} from './catalog-view.mjs';
import {recipeDescription} from './generation-recipe.mjs';
const el=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
export function createPictureView({scene,assets,onReroll,onListCandidates,onChooseCandidate,onDeleteCandidate,onRedraw,onSave,onSelect,onDelete,onClose}){
    const dialog=el('dialog',undefined,{class:'ad-picture','aria-label':'图片与人物管理'}),header=el('header'),image=el('img',undefined,{alt:'当前剧情插图'}),counter=el('p'),status=el('p','',{role:'status','aria-live':'polite',class:'ad-picture-status'});
    let index=assets.findIndex(a=>a.id===scene.selected_image),busy=false;if(index<0)index=Math.max(0,assets.length-1);
    const buttons=[],controls=el('aside',undefined,{class:'ad-picture-actions'}),figure=el('div',undefined,{class:'ad-picture-preview'}),layout=el('div',undefined,{class:'ad-picture-layout'}),history=el('div',undefined,{class:'ad-picture-history','aria-label':'图片历史'});
    async function run(fn){if(busy)return;busy=true;sync();status.setAttribute('role','status');status.textContent='正在处理…';try{const outcome=await fn();if(dialog.open)status.textContent=outcome===false?'已取消，图片保持原样。':'已完成。';}catch(error){status.textContent=error.message;status.setAttribute('role','alert');}finally{busy=false;sync();}}
    const button=(text,fn,attrs={})=>{const b=el('button',text,{type:'button',...attrs});b.onclick=()=>run(fn);buttons.push(b);return b;};
    const select=el('select',undefined,{'aria-label':'操作人物'});for(const actor of scene.actors)select.append(el('option',actor.person,{value:actor.person}));
    const interactionView=el('select',undefined,{'aria-label':'重绘互动镜头'});for(const[value,label]of[['auto','沿用本图镜头'],['pov','第一人称 · 对方手臂参与'],['third_person','第三人称 · 双人互动']])interactionView.append(el('option',label,{value}));interactionView.value='auto';const viewLabel=el('label','重绘互动镜头');viewLabel.append(interactionView);interactionView.disabled=!scene.interactions?.length;
    const partnerVisibility=el('select',undefined,{'aria-label':'互动对方入镜范围'});for(const[value,label]of[['hands','仅双手'],['arms','手臂与双手'],['torso','手臂与着装躯干'],['full','第三人称完整人物']])partnerVisibility.append(el('option',label,{value}));partnerVisibility.value=scene.interactions?.[0]?.partner_visibility||'torso';const visibilityLabel=el('label','互动对方入镜范围');visibilityLabel.append(partnerVisibility);const viewNote=el('p','普通双人互动可调整镜头与对方入镜范围；人物和衣装保持本图记录。',{class:'ad-picture-note'});
    const previous=button('上一张',async()=>{index=Math.max(0,index-1);await onSelect?.(assets[index]);render();}),next=button('下一张',async()=>{index=Math.min(assets.length-1,index+1);await onSelect?.(assets[index]);render();}),close=button('关闭',()=>dialog.close());
    const heading=el('div');heading.append(el('h2','图片与人物管理'),el('p',scene.summary||'查看图片，调整人物形象与动作。',{class:'ad-picture-caption'}));header.append(heading,close);const nav=el('div',undefined,{class:'ad-picture-nav'});nav.append(previous,counter,next);figure.append(image,nav,history);
    const actorLabel=el('label','操作人物');actorLabel.append(select);
    controls.append(el('h3','人物形象'),actorLabel,button('重抽角色形象',async()=>{if(onListCandidates&&onChooseCandidate){return await createCandidatePicker({name:select.value,onList:options=>onListCandidates(select.value,assets[index],options),onChoose:(id,options)=>onChooseCandidate(select.value,assets[index],id,options),onDelete:onDeleteCandidate}).finished;}else await onReroll(select.value,assets[index]);},{class:'ad-primary'}),button('保存角色形象',()=>onSave(select.value,assets[index])),el('p','新形象先试画，满意后保存。保存前沿用已绑定形象。',{class:'ad-picture-note'}),el('h3','这张图片'),viewLabel,visibilityLabel,viewNote,button('保留角色重绘',()=>onRedraw(assets[index],{interactionView:interactionView.value,partnerVisibility:partnerVisibility.value})),button('下载当前图片',()=>{const a=el('a');a.href=assets[index].data;a.download='剧情插图.png';a.click();}),button('删除当前图片',async()=>{await onDelete?.(assets[index]);assets.splice(index,1);if(!assets.length){dialog.close();return;}index=Math.min(index,assets.length-1);render();},{class:'ad-danger'}));
    const usage=el('section',undefined,{class:'ad-picture-usage'}),usageText=el('p');usage.append(el('h3','本图实际使用'),usageText);controls.append(usage);
    const params=el('details'),tags=el('pre');params.className='ad-picture-params';params.append(el('summary','查看本图 tags 与生成参数'),tags);layout.append(figure,controls);
    function sync(){for(const b of buttons)b.disabled=busy;previous.disabled=busy||index===0;next.disabled=busy||index===assets.length-1;select.disabled=busy||!scene.actors.length;interactionView.disabled=partnerVisibility.disabled=busy||!assets[index].scene_snapshot?.interactions?.length;viewNote.textContent=assets[index].scene_snapshot?.interactions?.length?'普通双人互动可调整镜头与对方入镜范围；人物和衣装保持本图记录。':'本图未保存双人动作关系。需要恢复普通双人互动时，请重新选段生图。';for(const b of history.querySelectorAll('button'))b.disabled=busy;}
    function render(){const asset=assets[index];image.src=asset.data;counter.textContent=(index+1)+' / '+assets.length;usageText.textContent=asset.recipe?recipeDescription(asset.recipe,asset.genParams):'旧图片未记录完整工作流快照，请查看下方原 tags 与生成参数。';tags.textContent=(asset.prompt||'')+'\n\n'+JSON.stringify({actual:asset.genParams||{},recipe:asset.recipe||null},null,2);history.replaceChildren();if(assets.length>1)assets.forEach((a,i)=>{const b=el('button',undefined,{type:'button','aria-label':'查看历史图片 '+(i+1),'aria-pressed':String(i===index)});b.append(el('img',undefined,{src:a.data,alt:'历史图片 '+(i+1)}));b.onclick=()=>run(async()=>{index=i;await onSelect?.(a);render();});history.append(b);});sync();}
    dialog.append(header,layout,status,params);document.body.append(dialog);dialog.addEventListener('close',()=>{onClose?.();dialog.remove();});render();dialog.showModal();return {close:()=>dialog.close(),isOpen:()=>dialog.open,setStatus:text=>{status.textContent=text;}};
}

/** Candidate selection is an explicit step. A candidate is never silently substituted. */
export function createCandidatePicker({name,onList,onChoose,onDelete,onClose}={}){
    const d=el('dialog',undefined,{class:'ad-manual ad-candidates','aria-label':'选择角色形象'}),header=el('header'),body=el('div',undefined,{class:'ad-manual-body'}),footer=el('footer'),list=el('div',undefined,{class:'ad-candidate-grid'}),status=el('p','正在查找人物形象…',{role:'status','aria-live':'polite',class:'ad-candidate-status'}),query=el('input',undefined,{type:'search','aria-label':'查找候选形象',placeholder:'角色名、作品名或外貌标签'}),searchRow=el('div',undefined,{class:'ad-candidate-search'}),manual=el('textarea',undefined,{rows:'5','aria-label':'手工人物 tags',spellcheck:'false',placeholder:'粘贴 Animadex 的完整人物串，可包含角色名字与 @画师名。'}),manualDetails=el('details'),notice=el('p','',{class:'ad-candidate-notice'});
    let selected=null,chosen=false,busy=false,epoch=0,candidates=[],relaxedMode=false,offset=0,total=0,pageSize=24,appliedFilters;let finish;const finished=new Promise(resolve=>{finish=resolve;});
    const button=(text,fn,attrs={})=>{const b=el('button',text,{type:'button',...attrs});b.onclick=fn;return b;};
    header.append(el('h2','为 '+name+' 选择形象'));const search=button('查找',()=>load(false,0)),relax=button('扩大候选范围',()=>load(true,0)),cancel=button('取消',()=>d.close()),choose=button('使用形象并重画',async()=>{if(busy)return;const useManual=manual.value.trim();if(!selected&&!useManual)return;busy=true;sync();status.setAttribute('role','status');status.textContent='正在使用所选形象重画…';try{await onChoose(useManual?'manual_tags':selected.id,{manualTags:useManual||undefined,relax:selected?.relaxed===true,filters:appliedFilters});chosen=true;d.close();}catch(error){status.textContent=error.message;status.setAttribute('role','alert');}finally{busy=false;sync();}},{class:'ad-primary'});
    const profile=el('details',undefined,{class:'ad-match-profile'}),criteria=el('p','',{class:'ad-match-criteria'}),filters=el('textarea',undefined,{rows:'2','aria-label':'外貌筛选标签',placeholder:'中文或英文外貌标签，以逗号分隔'}),apply=button('应用外貌条件',()=>{appliedFilters=filters.value;load(false,0);}),reset=button('恢复剧情条件',()=>{appliedFilters=undefined;load(false,0);});profile.open=true;profile.append(el('summary','剧情外貌条件'),criteria,filters,el('p','每项条件都必须匹配；同类发色、发长、瞳色的多个值为任选其一。年龄数字不等于源角色的已知年龄。',{class:'ad-library-muted'}),apply,reset);
    const pager=el('nav',undefined,{class:'ad-candidate-pages','aria-label':'候选分页'}),previous=button('上一页',()=>load(relaxedMode,Math.max(0,offset-pageSize))),next=button('下一页',()=>load(relaxedMode,offset+pageSize)),pageLabel=el('span','');pager.append(previous,pageLabel,next);
    const manualNote=el('p','手工串优先用于这次试画。满意后保存角色形象，后续图片才沿用它。',{class:'ad-library-muted'});manualDetails.append(el('summary','手工粘贴人物串'),manualNote,manual);searchRow.append(query,search);footer.append(cancel,choose);body.append(searchRow,profile,notice,list,pager,relax,manualDetails,status);d.append(header,body,footer);document.body.append(d);
    function sync(){choose.disabled=busy||(!selected&&!manual.value.trim());search.disabled=relax.disabled=apply.disabled=reset.disabled=busy;previous.disabled=busy||offset===0;next.disabled=busy||offset+pageSize>=total;query.disabled=manual.disabled=filters.disabled=busy;for(const b of list.querySelectorAll('button'))b.disabled=busy;d.setAttribute('aria-busy',String(busy));}
    function render(){list.replaceChildren();for(const candidate of candidates)list.append(prototypeCard(candidate,{selected:selected?.id===candidate.id,onSelect:()=>{selected=candidate;manual.value='';render();sync();},onDelete:onDelete?async c=>{await onDelete(c.id);await load(relaxedMode);}:undefined}));if(!candidates.length)list.append(el('p','此搜索没有候选。可以清空搜索、扩大范围，或粘贴自己的完整人物串。',{class:'ad-library-empty'}));}
    async function load(relaxed=false,start=0){if(busy)return;relaxedMode=relaxed;const turn=++epoch;busy=true;status.setAttribute('role','status');status.textContent='正在查找人物形象…';sync();try{const result=await onList({query:query.value.trim(),relax:relaxed,offset:start,limit:24,filters:appliedFilters});if(turn!==epoch||!d.open)return;candidates=Array.isArray(result)?result:result.candidates||[];selected=null;total=result.total??result.candidate_count??candidates.length;offset=result.offset??start;pageSize=result.limit??24;notice.textContent=[result.notice,...(result.profile?.warnings||[])].filter(Boolean).join(' ');if(result.profile){criteria.textContent=result.profile.criteria.map(c=>c.label+'（'+c.source+'）').join(' · ')+(result.profile.age?'；剧情年龄：'+result.profile.age:'');if(appliedFilters===undefined)filters.value=result.profile.filters;}relax.hidden=Array.isArray(result)?false:result.canRelax===false;render();pageLabel.textContent=total?`${offset+1}–${offset+candidates.length} / ${total}`:'0 / 0';status.textContent=`共 ${total} 个${relaxed?'扩大范围后的':'全部条件匹配的'}候选，当前展示 ${candidates.length} 个。按外貌相似度排序，热度仅作同分参考。`;}catch(error){if(turn===epoch){status.textContent=error.message;status.setAttribute('role','alert');}}finally{if(turn===epoch){busy=false;sync();}}}
    query.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();load(false);}};manual.oninput=()=>{if(manual.value.trim()){selected=null;render();}sync();};d.addEventListener('close',()=>{epoch++;onClose?.();finish(chosen);d.remove();});d.showModal();load();sync();return {dialog:d,finished,close:()=>d.close()};
}

/** The user chooses the person region rather than guessing identities in a multi-person image. */
export function chooseReference(asset,name,{multiple=false,referenceEnabled=false,onPreference}={}){return new Promise((resolve,reject)=>{
    const d=el('dialog',undefined,{class:'ad-manual','aria-label':'保存人物参考'}),body=el('div',undefined,{class:'ad-manual-body'});
    const img=el('img',undefined,{src:asset.data,alt:'选择 '+name+' 的人物区域',class:'ad-reference-preview'});
    body.append(el('h2','保存 '+name+' 的固定形象'),el('p',multiple?'请调整区域，只保留所选人物，避免保存其它人的外貌。':'保存这张满意图片。可以裁去背景，脸部参考还可以单独添加。'),img);
    const preference=el('label',undefined,{class:'ad-reference-preference'}),useReference=el('input',undefined,{type:'checkbox','aria-label':'用保存图片辅助后续生图'});useReference.checked=referenceEnabled;preference.append(useReference,el('span','用保存图片辅助后续生图（较慢）'));body.append(preference);
    const inputs={},fields=el('div',undefined,{class:'ad-reference-fields'});for(const [key,label,value]of [['x','左边界',0],['y','上边界',0],['w','区域宽度',100],['h','区域高度',100]]){const labelEl=el('label',label+'（%）');const input=el('input',undefined,{type:'number',min:'0',max:'100',value:String(value),'aria-label':label});labelEl.append(input);inputs[key]=input;fields.append(labelEl);}body.append(fields);
    const status=el('p','',{role:'status'}),footer=el('footer'),cancel=el('button','取消',{type:'button'}),save=el('button','保存此人物',{type:'button',class:'ad-primary'});
    cancel.onclick=()=>d.close();save.onclick=async()=>{try{await img.decode();const r=Object.fromEntries(Object.entries(inputs).map(([k,input])=>[k,Number(input.value)]));if(!Object.values(r).every(Number.isFinite)||r.w<=0||r.h<=0||r.x<0||r.y<0||r.x+r.w>100||r.y+r.h>100)throw new Error('裁剪区域超出图片。');if(multiple&&r.w===100&&r.h===100)throw new Error('多人图需要先选出这个人物的区域。');
        const canvas=document.createElement('canvas');canvas.width=Math.max(16,Math.round(img.naturalWidth*r.w/100));canvas.height=Math.max(16,Math.round(img.naturalHeight*r.h/100));canvas.getContext('2d').drawImage(img,img.naturalWidth*r.x/100,img.naturalHeight*r.y/100,canvas.width,canvas.height,0,0,canvas.width,canvas.height);onPreference?.(useReference.checked);resolve(canvas.toDataURL('image/png'));d.close();
    }catch(error){status.textContent=error.message;}};footer.append(cancel,save);body.append(status);d.append(body,footer);document.body.append(d);d.addEventListener('close',()=>{resolve(null);d.remove();});d.showModal();});}

