import {prototypeCard} from './catalog-view.mjs';
const el=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
const field=(name,input)=>{const label=el('label',undefined,{class:'ad-library-field'});label.append(el('span',name),input);return label;};
const split=v=>String(v).split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
const download=(data,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function buttons(notify){return(text,fn,attrs={})=>{const b=el('button',text,{type:'button',...attrs});b.onclick=async()=>{b.disabled=true;try{await fn();}catch(error){notify(error.message,'error');}finally{b.disabled=false;}};return b;};}
const valueZh={black:'黑色',white:'白色',blonde:'金色',brown:'棕色',red:'红色',blue:'蓝色',green:'绿色',purple:'紫色',pink:'粉色',grey:'灰色',silver:'银色',orange:'橙色',aqua:'青色',yellow:'黄色',short:'短发',medium:'中长发',long:'长发','very short':'极短发','very long':'超长发','absurdly long':'极长发'};
export function mountCatalogPane({pane,app,notify}){
    const button=buttons(notify),search=el('input',undefined,{type:'search','aria-label':'角色库搜索',placeholder:'角色名、作品名，多个条件用逗号分隔'}),tagInput=el('input',undefined,{type:'text','aria-label':'角色标签筛选',placeholder:'例如 ponytail, black hair'}),sort=el('select',undefined,{'aria-label':'角色库排序'}),scope=el('select',undefined,{'aria-label':'角色库范围'}),filters=el('div',undefined,{class:'ad-catalog-filters'}),facetInputs={},grid=el('div',undefined,{class:'ad-candidate-grid'}),status=el('p','',{class:'ad-library-muted',role:'status'}),pager=el('div',undefined,{class:'ad-catalog-pager'}),target=el('select',undefined,{'aria-label':'试用形象的人物'}),selectedText=el('p','先选一个形象，再给当前剧情人物试用。'),selectedTags=el('textarea',undefined,{'aria-label':'所选角色完整 tags',rows:'4',readonly:''}),choice=el('details',undefined,{class:'ad-catalog-choice'});
    let offset=0,epoch=0,loaded=false,selected=null,result={total:0,records:[]};sort.append(el('option','热度从高到低',{value:'popularity'}),el('option','角色名称',{value:'name'}));scope.append(el('option','扩充候选库',{value:'default'}),el('option','全部可选角色',{value:'all'}),el('option','已删除角色',{value:'deleted'}));
    const go=button('筛选角色',()=>load(true)),previous=button('上一页',()=>{offset=Math.max(0,offset-24);return load();}),next=button('下一页',()=>{offset+=24;return load();});pager.append(previous,status,next);
    pane.append(el('h3','Animadex 角色库'),el('p','按源库热度挑选形象。删除后不再自动抽到，已绑定的剧情人物与旧图片保留，可在已删除列表恢复。',{class:'ad-library-muted'}));filters.append(field('角色或作品',search),field('标签（多个取交集）',tagInput));for(const[f,label]of[['hair_color','发色'],['hair_length','发长'],['eye_color','瞳色'],['species','种族'],['ears','耳朵']]){const s=el('select',undefined,{'aria-label':'角色库'+label});s.append(el('option','不限',{value:''}));facetInputs[f]=s;filters.append(field(label,s));s.onchange=()=>load(true).catch(error=>notify(error.message,'error'));}filters.append(field('排序',sort),field('范围',scope),go);pane.append(filters,pager,grid);
    const trial=button('给此人物试用形象',async()=>{if(!selected||!target.value)throw new Error('先选一个形象和当前聊天人物。');await app.tryCatalogPerson(target.value,selected.id);notify('已用所选形象试画；满意后在图片管理中保存角色形象。');},{class:'ad-primary'});choice.append(el('summary','所选形象与人物试用'),selectedText,field('当前聊天人物',target),trial,field('完整人物 tags（可复制）',selectedTags));pane.append(choice);
    const backup=el('div',undefined,{class:'ad-library-actions'}),file=el('input',undefined,{type:'file',accept:'.json,application/json',hidden:'','aria-label':'导入角色库筛选'});file.onchange=async()=>{try{if(file.files[0]){await app.importCatalogChoices(JSON.parse(await file.files[0].text()));await load(true);}}catch(error){notify(error.message,'error');}finally{file.value='';}};backup.append(button('导出角色库筛选',()=>download(app.exportCatalogChoices(),'角色库筛选.json')),button('导入角色库筛选',()=>file.click()),file);pane.append(backup);
    function updatePeople(){const old=target.value,people=Object.values(app.getStory()?.cast.people||{}).filter(p=>!p.chosen_appearance_tags?.includes('1boy'));target.replaceChildren(el('option','选择剧情人物',{value:''}),...people.map(p=>el('option',p.person,{value:p.person})));if(people.some(p=>p.person===old))target.value=old;trial.disabled=!selected||!target.value||scope.value==='deleted';}
    function render(){grid.replaceChildren(...result.records.map(r=>prototypeCard(r,{selected:selected?.id===r.id,onSelect:record=>{selected=record;selectedText.textContent='已选：'+record.name;selectedTags.value=record.tags;choice.open=true;updatePeople();render();},onDelete:r.deleted?undefined:async record=>{await app.setCatalogDeleted(record.id,true);if(selected?.id===record.id){selected=null;selectedText.textContent='该形象已删除。';selectedTags.value='';}await load();},onRestore:r.deleted?async record=>{await app.setCatalogDeleted(record.id,false);await load();}:undefined})));
        if(!result.records.length)grid.append(el('p','没有匹配角色。可清空筛选或切换“全部可选角色”。',{class:'ad-library-empty'}));previous.disabled=offset===0;next.disabled=offset+24>=result.total;status.textContent=result.total+' 个角色 · '+(result.total?Math.floor(offset/24)+1:0)+' / '+Math.ceil(result.total/24)+' 页';}
    async function load(reset=false){if(reset)offset=0;const turn=++epoch,required={};for(const[f,s]of Object.entries(facetInputs))if(s.value)required[f]=s.value;status.textContent='正在筛选角色…';const got=await app.browseCatalog({text:search.value,required,tags:split(tagInput.value),offset,limit:24,sort:sort.value,all:scope.value==='all',deleted:scope.value==='deleted'});if(turn!==epoch)return;if(offset>=got.total&&offset>0){offset=Math.max(0,Math.floor((got.total-1)/24)*24);return load();}result=got;render();updatePeople();}
    search.onkeydown=tagInput.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();load(true).catch(error=>notify(error.message,'error'));}};sort.onchange=scope.onchange=()=>load(true).catch(error=>notify(error.message,'error'));target.onchange=updatePeople;
    async function refresh(){if(!loaded){const data=await app.catalogFacets();for(const[f,s]of Object.entries(facetInputs))for(const v of data.facets[f]||[])s.append(el('option',(valueZh[v.value]||v.value)+' ('+v.count+')',{value:v.value}));loaded=true;}updatePeople();return load();}
    return {refresh};
}
export function mountArtistPane({pane,app,notify}){
    const button=buttons(notify),select=el('select',undefined,{'aria-label':'默认画师'}),active=el('p','',{class:'ad-artist-active'}),list=el('div',undefined,{class:'ad-artist-list'}),name=el('input',undefined,{type:'text','aria-label':'画师预设名称',placeholder:'便于识别的名字'}),tags=el('input',undefined,{type:'text','aria-label':'画师预设标签',placeholder:'@画师名，多个用逗号分隔',spellcheck:'false'}),bulk=el('textarea',undefined,{rows:'4','aria-label':'批量导入画师文本',placeholder:'每行一个画师名，也可以粘贴画师 JSON'}),file=el('input',undefined,{type:'file',accept:'.json,.txt,application/json,text/plain',hidden:'','aria-label':'导入画师文件'});let editing='';
    const form=el('section',undefined,{class:'ad-artist-form'});form.append(el('h4','添加或编辑画师'),field('画师名称',name),field('实际加入的 tags',tags),button('保存画师预设',()=>{app.saveArtistPreset({id:editing||undefined,name:name.value,tags:split(tags.value).map(t=>t.startsWith('@')?t:'@'+t)});editing='';name.value=tags.value='';render();notify('画师预设已保存。');},{class:'ad-primary'}),button('清空编辑',()=>{editing='';name.value=tags.value='';}));
    pane.append(el('h3','画风与画师'),el('p','选中的默认画师用于后续自动生图、选段生图和重绘，最终加入 @画师标签。切换为“不添加默认画师”即可停用。',{class:'ad-library-muted'}),field('后续图片的默认画师',select),active,list,form,el('h4','导入与导出'),bulk,button('批量导入画师',()=>{const added=app.importArtists(bulk.value);bulk.value='';render();notify('已添加 '+added.length+' 个画师预设。');}));
    const actions=el('div',undefined,{class:'ad-library-actions'});actions.append(button('导入画师文件',()=>file.click()),button('导出全部画师',()=>download(app.exportArtists(),'画师预设.json')),file);pane.append(actions);
    select.onchange=()=>{try{app.setDefaultArtist(select.value);render();}catch(error){notify(error.message,'error');}};
    file.onchange=async()=>{try{if(file.files[0]){const added=app.importArtists(await file.files[0].text());render();notify('已导入 '+added.length+' 个画师预设。');}}catch(error){notify(error.message,'error');}finally{file.value='';}};
    function render(){const prefs=app.getDrawingPreferences();select.replaceChildren(el('option','不添加默认画师',{value:''}),...prefs.artists.map(a=>el('option',a.name+' · '+a.tags.join(', '),{value:a.id})));select.value=prefs.defaultArtistId;active.textContent=prefs.defaultArtistTags.length?'后续图片默认加入：'+prefs.defaultArtistTags.join(', '):'当前沿用模型或人物档案的画风。';list.replaceChildren();for(const artist of prefs.artists){const row=el('article',undefined,{class:'ad-artist-card'});row.append(el('strong',artist.name+(artist.id===prefs.defaultArtistId?' · 当前默认':'')),el('code',artist.tags.join(', ')),button('设为默认',()=>{app.setDefaultArtist(artist.id);render();}),button('编辑画师',()=>{editing=artist.id;name.value=artist.name;tags.value=artist.tags.join(', ');name.focus();}),button('删除画师',()=>{app.deleteArtistPreset(artist.id);if(editing===artist.id){editing='';name.value=tags.value='';}render();},{class:'ad-danger'}));list.append(row);}if(!prefs.artists.length)list.append(el('p','还没有画师。可以逐个添加，或批量导入名称和标签。',{class:'ad-library-empty'}));}
    render();return {refresh:render};
}
