import {createLibrary,newStory} from './story-library.mjs';
import {readControl,prepareCapture,prepareLegacyFrame,priorOutfitsFor,compileFrame,rerollActor,frameState,narrativeOffset,automaticSource} from './automatic-scene.mjs';
import {applyOutfit,outfitText,legacyOutfit} from './wardrobe-state.mjs';
import {scenePrompt,sourceHash,locateExcerpt,proseOf,proseRange,validateConfirmedPrompt,compileScene,restoredSceneMessages} from './scene-planner.mjs';
import {prepareManualScene,requestManualFlash} from './manual-scene.mjs';
import {createManualView} from './manual-view.mjs';
import {installSelectionMenu} from './selection-menu.mjs';
import {createPictureView,chooseReference} from './picture-view.mjs';
import {hostChatKey} from './studio-persistence.mjs';
import {usesImageReference,migrateIdentityFlags} from './identity.mjs';
import {findPerson,listActorCandidates,artistTags} from './character-tools.mjs';
import {createWorkflowLibrary} from './workflow-library.mjs';
import {RENDER_POLICY} from './render-policy.mjs';
import {focusFrame} from './render-policy.mjs';
import {ARTIST_FORMAT,normalizeArtist,parseArtistImport,withDefaultArtists} from './drawing-preferences.mjs';
import {createManualTransport,manualConnection} from './manual-transport.mjs';
import {automaticPrompt} from './automatic-instruction.mjs';
import {createDomRefresh,changedChatRows} from './dom-refresh.mjs';
import {createRenderQueue} from './render-queue.mjs';
import {openParagraphPicker} from './paragraph-picker.mjs';
import {generationRecipe} from './generation-recipe.mjs';
import {inspectRenderConfig} from './generation-health.mjs';
import {reconcileStoryAppearance,storyContext} from './narrative-appearance.mjs';
const clone=structuredClone;
const sameAppearance=(a,b)=>!!a&&!!b&&['prototype_id','age_description','face_description'].every(k=>(a[k]||'')===(b[k]||''))&&JSON.stringify(a.chosen_appearance_tags||[])===JSON.stringify(b.chosen_appearance_tags||[]);
export function createStoryApp({getContext,getTools,persist,setting,notify,diagnostics,library=createLibrary(),fetcher=fetch}){
    const manualRequester=createManualTransport({getContext,setting,fetcher,onRequest:info=>diagnostics?.({event:'manual_request_started',...info})});
    const workflows=createWorkflowLibrary({native:()=>getContext().extensionSettings['st-chatu8']||{},save:()=>getContext().saveSettingsDebounced?.()});
    let story,activeKey='',turn=0,chain=Promise.resolve(),manual,picture,selection,paragraphPicker,abort;const jobs=new Map(),uploads=new Map(),responses=new Map(),handlingResponses=new Set();
    let automaticStatus={state:'idle',reason:'等待新的回复',message_id:null},loadFloor=-1,generationKey='',generationFloor=-1;
    function beginGeneration(type){if(type==='quiet')return;generationKey=key();generationFloor=getContext().chat.length-1;}
    const taskChanged=()=>window.dispatchEvent(new CustomEvent('animadex-tasks-updated'));
    const taskValid=task=>task.key===key()&&task.key===activeKey&&enabled()&&(!task.automatic||setting().automatic!==false&&setting().automatic_render===true)&&story?.scenes[task.scene.id]?.revision===task.scene.revision&&sourceHash(getContext().chat[task.scene.message_id]?.mes||'')===task.scene.source_hash&&(getContext().chat[task.scene.message_id]?.swipe_id??0)===task.scene.swipe_id;
    const renderQueue=createRenderQueue({valid:taskValid,onChange:taskChanged,run:async task=>{
        inspectRenderConfig(getContext().extensionSettings['st-chatu8'],task.scene);
        const request=task.request;await new Promise((resolve,reject)=>{
            const timer=setTimeout(()=>{responses.delete(request.id);reject(new Error('生图结果等待超时，后续任务已暂停。请检查智绘姬与 ComfyUI 后再重试。'));},600000);
            responses.set(request.id,{task,resolve:()=>{clearTimeout(timer);responses.delete(request.id);resolve();},reject:error=>{clearTimeout(timer);responses.delete(request.id);reject(error);}});
            Promise.resolve(getContext().eventSource.emit('generate-image-request',request)).then(()=>{if(request.animadexAbort)responses.get(request.id)?.reject(new Error(request.animadexAbort));}).catch(error=>responses.get(request.id)?.reject(error));
        });
    }});
    const autoStatus=(state,reason,message_id)=>{automaticStatus={state,reason,message_id,time:Date.now()};taskChanged();};
    const enabled=()=>setting().enabled!==false;
    const key=()=>hostChatKey(getContext());
    const check=(expected)=>{if(key()!==expected||activeKey!==expected)throw new Error('已切换聊天，本次操作取消。');};
    const enqueue=fn=>{const task=chain.then(fn);chain=task.catch(()=>{});return task;};
    const savePreferences=()=>{getContext().saveSettingsDebounced?.();window.dispatchEvent(new CustomEvent('animadex-preferences-updated'));};
    const drawingPreferences=()=>({artists:clone(setting().artist_presets||[]),defaultArtistId:setting().default_artist_id||'',defaultArtistTags:clone(setting().default_artist_tags||[]),deletedIds:clone(setting().catalog_excluded_ids||[])});
    function applyArtistPreference(scene){const tags=artistTags(setting().default_artist_tags||[]);scene.confirmed_prompt=withDefaultArtists(compileFrame(scene),tags,scene.default_artist_tags||[]);scene.default_artist_tags=tags;return scene;}
    async function browseCatalog(options){const {catalog}=await getTools();return catalog.browse(options);}
    async function catalogFacets(){const {catalog}=await getTools();return {facets:catalog.browseFacets(),stats:catalog.stats};}
    async function setCatalogDeleted(id,deleted=true){const {catalog}=await getTools();if(!catalog.get(id))throw new Error('角色原型不存在。');const ids=new Set(setting().catalog_excluded_ids||[]);if(deleted)ids.add(id);else ids.delete(id);setting().catalog_excluded_ids=[...ids];savePreferences();}
    function saveArtistPreset(value){const preset=normalizeArtist(value),s=setting(),records=clone(s.artist_presets||[]),id=value.id||'artist_'+crypto.randomUUID().replaceAll('-','');const same=records.find(r=>r.id!==id&&r.tags.join(',')===preset.tags.join(','));if(same)return same;if(records.some(r=>r.id!==id&&r.name===preset.name))throw new Error('已存在同名画师，请使用不同名称。');const next={id,...preset},at=records.findIndex(r=>r.id===id);if(at<0)records.push(next);else records[at]=next;s.artist_presets=records;if(s.default_artist_id===id)s.default_artist_tags=next.tags;savePreferences();return clone(next);}
    function importArtists(input){const validated=parseArtistImport(input),s=setting(),records=clone(s.artist_presets||[]),added=[];for(const row of validated){if(records.some(r=>r.tags.join(',')===row.tags.join(',')))continue;let name=row.name,n=2;while(records.some(r=>r.name===name))name=row.name+' ('+(n++)+')';const record={id:'artist_'+crypto.randomUUID().replaceAll('-',''),name,tags:row.tags};records.push(record);added.push(record);}s.artist_presets=records;savePreferences();return added;}
    function setDefaultArtist(id=''){const s=setting(),p=(s.artist_presets||[]).find(r=>r.id===id);if(id&&!p)throw new Error('画师预设不存在。');s.default_artist_id=id;s.default_artist_tags=p?artistTags(p.tags):[];savePreferences();}
    function deleteArtistPreset(id){const s=setting();s.artist_presets=(s.artist_presets||[]).filter(r=>r.id!==id);if(s.default_artist_id===id){s.default_artist_id='';s.default_artist_tags=[];}savePreferences();}
    async function importCatalogChoices(data){const {catalog}=await getTools();if(data?.format!=='animadex-catalog-choices-v1'||!Array.isArray(data.deletedIds)||data.deletedIds.some(id=>typeof id!=='string'||!catalog.get(id)))throw new Error('请选择本插件导出的角色库筛选备份。');setting().catalog_excluded_ids=[...new Set([...(setting().catalog_excluded_ids||[]),...data.deletedIds])];savePreferences();}
    async function tryCatalogPerson(name,id){const expected=activeKey;check(expected);const scene=Object.values(story.scenes).reverse().find(s=>s.actors?.some(a=>a.person===name)&&s.source_hash===sourceHash(getContext().chat[s.message_id]?.mes||'')&&s.swipe_id===(getContext().chat[s.message_id]?.swipe_id??0));if(!scene)throw new Error('该人物还没有当前剧情的插图按钮，请先自动出按钮或选段生图。');const tools=await getTools();check(expected);const next=rerollActor(scene,name,{...tools,state:story.cast,candidateId:id,relax:true});await revise(next);}
    const fingerprint=text=>{let value=2166136261;for(const c of String(text))value=Math.imul(value^c.charCodeAt(0),16777619);return (value>>>0).toString(16);};
    function refreshPendingPerson(next,name,person){for(const scene of Object.values(next.scenes)){if(!scene.automatic||scene.images?.length||[...jobs.values()].some(job=>job.scene.id===scene.id))continue;let changed=false;for(const actor of scene.actors)if(actor.person===name){actor.person_snapshot=clone(person);changed=true;}if(changed){scene.style=scene.actors[0]?.person_snapshot.style||scene.style;delete scene.confirmed_prompt;scene.confirmed_prompt=compileFrame(scene);}}}
    async function load(){const expected=key();const epoch=++turn;renderQueue.cancelQueued('聊天已重新加载');loadFloor=getContext().chat.length-1;abort?.abort();manual?.close();picture?.close();selection?.close();paragraphPicker?.close();const next=await library.getStory(expected);if(epoch!==turn||key()!==expected)return;
        activeKey=expected;story=next||newStory(expected,getContext().chatMetadata?.animadex_cast_v1);if(!next){for(const p of Object.values(story.cast.people)){p.version=1;p.accepted=false;p.style_chosen=true;}
            const old=getContext().chatMetadata?.animadex_scenes_v1;for(const [id,scene]of Object.entries(old?.scenes||{})){const s=clone(scene);s.images=[];for(const a of s.actors||[]){a.person_snapshot=clone(Object.values(story.cast.people).find(p=>p.person===a.person));a.outfit=legacyOutfit(a.wardrobe);}story.scenes[id]=s;}
            story=await library.saveStory(story,0);}
        if(Object.keys(story.cast.people).length){const tools=await getTools();if(epoch!==turn||key()!==expected)return;const migrated=clone(story);let changed=migrateIdentityFlags(migrated.cast.people,tools.catalog);const names=Object.values(migrated.cast.people).map(p=>p.person),text=storyContext(getContext().chat,getContext().chat.length-1,Infinity,proseOf);for(const p of Object.values(migrated.cast.people)){if(!p.story_appearance)p.appearance_migration_backup={tags:clone(p.chosen_appearance_tags),trigger_enabled:p.trigger_enabled,age_description:p.age_description,face_description:p.face_description};if(reconcileStoryAppearance(p,{text,catalog:tools.catalog,names})){changed=true;refreshPendingPerson(migrated,p.person,p);}}if(changed)story=await library.saveStory(migrated,story.revision);if(epoch!==turn||key()!==expected)return;}
        for(const change of restoredSceneMessages(story,getContext().chat)){
            if(epoch!==turn||key()!==expected)return;
            await persist({expectedKey:expected,messageId:change.messageId,expectedRaw:change.raw,nextMessage:change.nextMessage});
            if(epoch!==turn||key()!==expected)return;
            getContext().updateMessageBlock?.(change.messageId,getContext().chat[change.messageId]);
        }
        autoStatus('idle','等待新的回复；历史插图不会自动补画',null);anchors();mount();window.dispatchEvent(new CustomEvent('animadex-library-updated'));return story;
    }
    async function commit(next,{messageId,raw,nextMessage}={}){
        const expected=activeKey;check(expected);const previous=clone(story);const saved=await library.saveStory(next,story.revision);
        try{check(expected);if(nextMessage!==undefined)await persist({expectedKey:expected,messageId,expectedRaw:raw,nextMessage,patchMetadata:{animadex_library_v2:{id:expected}}});}
        catch(error){await library.saveStory({...previous,revision:saved.revision},saved.revision);if(key()===expected)story=await library.getStory(expected);throw error;}
        check(expected);story=saved;anchors();mount();window.dispatchEvent(new CustomEvent('animadex-library-updated'));return saved;
    }
    function anchors(){const ctx=getContext();
        const id=ctx.chat.length-1,m=ctx.chat[id],outfits=story?priorOutfitsFor(story,{messageId:id,swipeId:m?.swipe_id??0,offset:String(m?.mes||'').length,chat:ctx.chat}):{};
        ctx.setExtensionPrompt?.('animadex_story_cast',automaticPrompt(story,setting(),outfits),1,0,false);
    }
    async function processMessage(messageId,{fresh=false}={}){
        if(!enabled()||setting().automatic===false){autoStatus('disabled','自动插图已关闭',messageId);return;}const ctx=getContext();if(ctx.streamingProcessor?.isFinished===false){autoStatus('streaming','等待正文回复完成',messageId);return;}const expected=key(),message=ctx.chat[messageId];if(!message||message.is_user||message.is_system)return;
        if(!story||activeKey!==expected)await load();check(expected);const raw=String(message.mes||''),hash=sourceHash(raw),swipe=message.swipe_id??0;
        const source=automaticSource(raw);
        if(!proseOf(source).trim()){autoStatus('empty_reply','这条主对话正文为空，请重试对话后再绘图。',messageId);return;}
        if(/^\s*\[API\s*(?:错误|Error)\]/i.test(proseOf(source))){autoStatus('reply_error','主对话接口报错，请重试对话后再绘图。',messageId);return;}
        const blocks=[...source.matchAll(/image###([\s\S]*?)###/g)].filter(m=>m[1].includes('ADCAP')||/^\s*Scene Composition\s*:/i.test(m[1]));
        const memories=[...source.matchAll(/<!--\s*ADMEM([\s\S]*?)END\s*-->/g)];if(!blocks.length&&!memories.length){if(!/image###ADSCENE/.test(source))autoStatus('no_marker','这条回复没有可见的插图标记，可用选段生图',messageId);return;}
        const token=messageId+':'+swipe+':'+hash,processed=token+':'+fingerprint(memories.map(m=>m[1]).join('\n'));if(story.processed[processed]&&!blocks.length)return;
        const tools=await getTools();check(expected);if(ctx.chat[messageId]?.mes!==raw)throw new Error('正文正在变化，稍后重新准备。');
        const next=clone(story);let outfits=priorOutfitsFor(next,{messageId,swipeId:swipe,offset:0,chat:ctx.chat});const replacements=[];
        const steps=[...memories.map(m=>({type:'memory',offset:m.index,m})),...blocks.map(m=>({type:'image',offset:m.index,m}))].sort((a,b)=>a.offset-b.offset);
        for(const step of steps){
            const position=narrativeOffset(raw,step.offset);
            if(step.type==='memory'){const value=JSON.parse(step.m[1]);if(value.v!==2||!Array.isArray(value.people)||value.people.length>4||value.people.some(a=>typeof a.name!=='string'||!a.name.trim()||['__proto__','constructor','prototype'].includes(a.name)))throw new Error('衣装变化记录格式不正确。');for(const actor of value.people)outfits[actor.name]=applyOutfit(outfits[actor.name],actor.outfit);next.events[token+':memory:'+position]={message_id:messageId,swipe_id:swipe,source_hash:hash,offset:position,offset_kind:'prose',people:value.people};continue;}
            const control=readControl(step.m[1]);const legacy=!control&&/^\s*Scene Composition\s*:/i.test(step.m[1]);if(!control&&!legacy)throw new Error('自动插图缺少 ADCAP v2 人物信息。');
            const captureHash=fingerprint(control?JSON.stringify(control.value):step.m[1]),prior=Object.values(next.scenes).find(s=>s.automatic&&s.message_id===messageId&&s.swipe_id===swipe&&s.source_hash===hash&&s.prose_offset===position);
            if(prior?.capture_hash===captureHash){for(const a of prior.actors)outfits[a.person]=a.outfit;replacements.push([step.m.index,step.m[0].length,'image###'+scenePrompt(prior.id,prior.revision)+'###']);continue;}
            const id=prior?.id||'sc_'+crypto.randomUUID().replaceAll('-','');const result=(legacy?prepareLegacyFrame:prepareCapture)(legacy?step.m[1]:control.value,{state:next.cast,resolver:tools.resolver,catalog:tools.catalog,id,messageId,swipeId:swipe,raw,start:step.offset,end:step.offset+step.m[0].length,priorOutfits:outfits,appearanceContext:storyContext(ctx.chat,messageId,step.offset,proseOf)});result.scene.prose_offset=position;result.scene.capture_hash=captureHash;if(prior){const old=clone(prior);delete old.history;result.scene.revision=prior.revision+1;result.scene.images=prior.images||[];result.scene.selected_image=prior.selected_image;result.scene.history=[...(prior.history||[]),old];}
            result.scene.excerpt=proseOf(raw.slice(Math.max(0,step.offset-2500),step.offset)).trim().slice(-1500);
            next.cast=result.state;next.scenes[id]=result.scene;const people=result.scene.actors.map(a=>({name:a.person,outfit:{mode:'snapshot',items:a.outfit.items}}));
            next.events[token+':image:'+id]={message_id:messageId,swipe_id:swipe,source_hash:hash,offset:position,offset_kind:'prose',people};for(const a of result.scene.actors)outfits[a.person]=a.outfit;
            replacements.push([step.m.index,step.m[0].length,'image###'+scenePrompt(id,result.scene.revision)+'###']);
        }
        next.processed[processed]=true;let text=raw;for(const [at,length,replacement]of replacements.reverse())text=text.slice(0,at)+replacement+text.slice(at+length);
        await commit(next,{messageId,raw,nextMessage:text});ctx.updateMessageBlock?.(messageId,ctx.chat[messageId]);diagnostics?.({event:'automatic_local_ready',pictures:blocks.length,flash_calls:0});
        const prepared=Object.values(story.scenes).filter(s=>s.automatic&&s.message_id===messageId&&s.source_hash===hash&&s.swipe_id===swipe);
        const limit=Math.max(1,Math.min(3,Number(setting().automatic_max_images)||1));
        const freshFloor=generationKey===expected?generationFloor:loadFloor;
        if(fresh&&messageId>freshFloor&&setting().automatic_render===true&&prepared.length){
            for(const scene of prepared.slice(0,limit))generate(scene,{automatic:true});
            autoStatus('queued','已准备 '+prepared.length+' 个按钮，本条自动生成 '+Math.min(limit,prepared.length)+' 张；其余可手动生成',messageId);
        }else autoStatus('prepared',prepared.length+' 个插图按钮已准备；'+(setting().automatic_render===true?'历史或重新编辑的回复不会自动补画':'当前仅准备按钮'),messageId);
    }
    function snapshotSelection(){if(!enabled()||!story)return null;const selected=window.getSelection();if(!selected?.rangeCount||selected.isCollapsed)return null;const range=selected.getRangeAt(0),start=range.startContainer.nodeType===1?range.startContainer:range.startContainer.parentElement,end=range.endContainer.nodeType===1?range.endContainer:range.endContainer.parentElement;const mes=start.closest?.('#chat .mes_text');if(!mes||!mes.contains(end))return null;
        const row=mes.closest('.mes'),id=Number(row?.getAttribute('mesid')),ctx=getContext(),message=ctx.chat[id];if(!message||message.is_user)return null;const raw=String(message.mes);const prefix=range.cloneRange();prefix.selectNodeContents(mes);prefix.setEnd(range.startContainer,range.startOffset);const location=locateExcerpt(raw,selected.toString(),{prefix:prefix.toString().slice(-200)});if(!proseRange(raw,location.start,location.end))return null;
        return {chatKey:key(),messageId:id,swipeId:message.swipe_id??0,raw,selected:location,excerpt:raw.slice(location.start,location.end)};
    }
    function checkSnapshot(s){check(s.chatKey);const m=getContext().chat[s.messageId];if(m?.mes!==s.raw||(m.swipe_id??0)!==s.swipeId)throw new Error('原文或回复分支已变化，请重新选段。');}
    async function openManual(s){checkSnapshot(s);manual?.close();abort?.abort();const epoch=++turn;const initialRevision=story.revision;let result;
        const onPrepare=async(correction='')=>{abort=new AbortController();checkSnapshot(s);const tools=await getTools();const state=clone(story.cast);const outfits=priorOutfitsFor(story,{messageId:s.messageId,swipeId:s.swipeId,offset:s.selected.start,chat:getContext().chat});for(const p of Object.values(state.people)){if(outfits[p.person])p.wardrobe={description:outfitText(outfits[p.person]),tags:[]};else if(s.messageId<getContext().chat.length-1)delete p.wardrobe;}
            const prepared=await prepareManualScene(s,{chat:clone(getContext().chat),state,resolver:tools.resolver,fetcher,requester:manualRequester,signal:abort.signal,wardrobeSchema:2,correction,priorOutfits:outfits});if(epoch!==turn)throw new Error('窗口已经关闭。');checkSnapshot(s);if(story.revision!==initialRevision)throw new Error('人物记录已更新，请重新选段。');
            for(const actor of prepared.scene.actors){const p=Object.values(prepared.state.people).find(p=>p.person===actor.person);p.version??=1;p.accepted??=false;actor.person_snapshot=clone(p);actor.outfit??=legacyOutfit(actor.wardrobe);}
            applyArtistPreference(prepared.scene);result=prepared;return prepared;};
        manual=createManualView({onPrepare,onConfirm:async prepared=>enqueue(async()=>{checkSnapshot(s);if(epoch!==turn||story.revision!==initialRevision)throw new Error('记录已经改变，请重新准备。');const next=clone(story),scene=prepared.scene;scene.confirmed_prompt=validateConfirmedPrompt(scene.confirmed_prompt);scene.images=[];scene.status='saved';
            const duplicate=Object.values(next.scenes).find(x=>x.manual&&x.message_id===s.messageId&&x.swipe_id===s.swipeId&&x.source_hash===sourceHash(s.raw)&&x.anchor===scene.anchor);let text;
            if(duplicate){scene.id=duplicate.id;scene.revision=duplicate.revision+1;scene.images=duplicate.images||[];text=s.raw.replace('image###'+scenePrompt(duplicate.id,duplicate.revision)+'###','image###'+scenePrompt(scene.id,scene.revision)+'###');}
            else text=s.raw.slice(0,s.selected.end)+'\n\nimage###'+scenePrompt(scene.id,scene.revision)+'###\n\n'+s.raw.slice(s.selected.end);
            next.cast=prepared.state;next.scenes[scene.id]=scene;await commit(next,{messageId:s.messageId,raw:s.raw,nextMessage:text});getContext().updateMessageBlock?.(s.messageId,getContext().chat[s.messageId]);notify('图片按钮已保存。');}),onClose:()=>{abort?.abort();turn++;}});manual.open(s);
    }
    async function assetData(src){if(/^data:image\/(png|jpeg|webp);base64,/.test(src))return src;const r=await fetcher(src);if(!r.ok)throw new Error('无法保存图片副本。');const blob=await r.blob();if(!/^image\/(png|jpeg|webp)/.test(blob.type))throw new Error('返回的文件不是图片。');return await new Promise((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(f.result);f.onerror=()=>reject(f.error);f.readAsDataURL(blob);});}
    async function saveAsset(src,scene,genParams,recipe){const data=await assetData(src),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(data+'\0'+scene.id+'\0'+scene.revision+'\0'+crypto.randomUUID()));const id='img_'+[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');const asset={id,data,scene_id:scene.id,prompt:compileFrame(scene),scene_snapshot:clone(scene),genParams:genParams||{},recipe,created_at:new Date().toISOString()};await library.saveAsset(asset);return asset;}
    async function uploadReference(id){const ctx=getContext(),url=String(ctx.extensionSettings['st-chatu8']?.comfyuiUrl||'').replace(/\/$/,'');if(!/^https?:\/\//.test(url))throw new Error('智绘姬 ComfyUI 地址未配置。');const cacheKey=url+':'+id;if(uploads.has(cacheKey))return uploads.get(cacheKey);const asset=await library.getAsset(id);if(!asset)throw new Error('人物参考图片丢失，请重新保存形象。');const blob=await (await fetcher(asset.data)).blob(),form=new FormData();form.append('image',blob,id+'.png');form.append('subfolder','AnimadexIdentity');form.append('overwrite','true');const r=await fetcher(url+'/upload/image',{method:'POST',body:form});if(!r.ok)throw new Error('人物参考上传失败：HTTP '+r.status);const value=await r.json(),filename=value.subfolder+'/'+value.name;uploads.set(cacheKey,filename);return filename;}
    async function bridge(request){if(!/ADSCENE|ADCAP/.test(request.prompt||''))return false;const expected=key();try{if(!story||activeKey!==expected)await load();check(expected);if(!enabled())throw new Error('剧情绘图已停用。');const id=readControl(request.prompt,'ADSCENE')?.value.id,scene=story.scenes[id];if(!scene)throw new Error('这张图还未准备完成，请等回复结束后重试。');const revision=readControl(request.prompt,'ADSCENE').value.rev??1;if(revision!==scene.revision)throw new Error('图片按钮版本已更新，请使用新按钮。');const message=getContext().chat[scene.message_id];if(!message||sourceHash(message.mes)!==scene.source_hash||(message.swipe_id??0)!==scene.swipe_id)throw new Error('图片对应原文或分支已改变，请重新准备。');
        if(jobs.has(request.id))return true;
        const repaired=clone(scene);if(repaired.actors?.length&&!repaired.appearance_contract_version&&!repaired.tags_user_edited){const tools=await getTools(),text=storyContext(getContext().chat,scene.message_id,scene.start,proseOf),names=Object.values(story.cast.people).map(p=>p.person);for(const actor of repaired.actors){const saved=findPerson(story.cast.people,actor.person)?.[1];if(saved?.story_appearance?.source==='user')actor.person_snapshot=clone(saved);else reconcileStoryAppearance(actor.person_snapshot,{text,catalog:tools.catalog,names});}delete repaired.confirmed_prompt;repaired.appearance_contract_version=1;}
        if(repaired.actors?.length===2&&!repaired.actor_binding_version&&!repaired.tags_user_edited&&!repaired.manual){delete repaired.confirmed_prompt;repaired.actor_binding_version=1;}
        const snapshot=applyArtistPreference(repaired),references=[];for(let slot=0;slot<4&&references.length<4;slot++)for(const actor of snapshot.actors){if(!usesImageReference(actor.person_snapshot))continue;const id=actor.person_snapshot?.reference_ids?.[slot];if(id&&!references.includes(id)&&references.length<4)references.push(id);}if(references.length)inspectRenderConfig(getContext().extensionSettings['st-chatu8'],snapshot);const files=[];for(const id of references)files.push(await uploadReference(id));check(expected);
        request.change=compileFrame(snapshot);request.castPrepared=true;request.animadexSceneReady=true;request.animadexStyle=snapshot.style;request.animadexSeed=Math.floor(Math.random()*Number.MAX_SAFE_INTEGER);request.animadexReferenceFiles=[...new Set(files)].slice(0,4);request.animadexValidate=()=>key()!==expected?'已切换聊天，本次绘图停止。':!enabled()?'剧情绘图已停用。':sourceHash(getContext().chat[snapshot.message_id]?.mes||'')!==snapshot.source_hash||(getContext().chat[snapshot.message_id]?.swipe_id??0)!==snapshot.swipe_id||story.scenes[snapshot.id]?.revision!==snapshot.revision?'正文、分支或图片按钮已变化，本次绘图停止。':'';jobs.set(request.id,{key:expected,scene:snapshot,recipe:generationRecipe(snapshot,getContext().extensionSettings['st-chatu8'],request),started:performance.now()});taskChanged();
    }catch(error){request.animadexAbort=error.message;request.change='';notify(error.message,'error');}return true;}
    async function returned(data){const job=jobs.get(data.id);if(!job)return;jobs.delete(data.id);if(!data.success||!data.imageData)throw new Error(data.error||'未收到图片');const asset=await saveAsset(data.imageData,job.scene,data.genParams,job.recipe);const queued=responses.get(data.id);if(queued)queued.task.saved_asset_id=asset.id;
        await enqueue(async()=>{for(let attempt=0;attempt<3;attempt++){const next=await library.getStory(job.key),scene=next?.scenes[job.scene.id];if(!scene)return;
            if(scene.revision===job.scene.revision){scene.images=[...(scene.images||[]),asset.id];scene.hide_images=false;scene.selected_image=asset.id;}
            else scene.archived_images=[...(scene.archived_images||[]),asset.id];
            try{const saved=await library.saveStory(next,next.revision);if(key()===job.key&&activeKey===job.key){story=saved;anchors();mount();window.dispatchEvent(new CustomEvent('animadex-library-updated'));}break;}catch(error){if(attempt===2)throw error;}}});
        if(key()===job.key&&activeKey===job.key){getContext().updateMessageBlock?.(job.scene.message_id,getContext().chat[job.scene.message_id]);mount();}diagnostics?.({event:'picture_saved',scene_id:job.scene.id,reference_used:job.scene.actors.some(a=>usesImageReference(a.person_snapshot)&&a.person_snapshot?.reference_ids?.length),elapsed_s:(performance.now()-job.started)/1000});}
    function generate(scene,{automatic=false}={}){check(activeKey);const id='ad2_'+crypto.randomUUID(),request={id,prompt:scenePrompt(scene.id,scene.revision)};const token=automatic?activeKey+':'+scene.id+':'+scene.revision:id;renderQueue.add({id,request,key:activeKey,scene:clone(scene),automatic,token});return request;}
    async function revise(scene,{draw=true,images}={}){return enqueue(async()=>{const next=clone(story),old=next.scenes[scene.id],message=getContext().chat[old.message_id],raw=message.mes;const prior=clone(old);delete prior.history;scene.history=[...(old.history||[]),prior];scene.revision=old.revision+1;scene.confirmed_prompt=validateConfirmedPrompt(scene.confirmed_prompt);scene.images=images??old.images??[];scene.source_hash=sourceHash(raw);next.scenes[scene.id]=clone(scene);const text=raw.replace('image###'+scenePrompt(old.id,old.revision)+'###','image###'+scenePrompt(scene.id,scene.revision)+'###');if(text===raw)throw new Error('原图片按钮已改变，请重新打开图片。');await commit(next,{messageId:old.message_id,raw,nextMessage:text});getContext().updateMessageBlock?.(old.message_id,getContext().chat[old.message_id]);if(draw)await generate(scene);});}
    async function openPicture(sceneId,src){const expected=key();check(expected);const scene=story.scenes[sceneId];if(!scene)throw new Error('图片记录缺失。');let assets=[];for(const id of [...new Set([...(scene.images||[]),...(scene.archived_images||[])])]){const asset=await library.getAsset(id);if(asset)assets.push(asset);}if(!assets.length&&src){const asset=await saveAsset(src,scene);await enqueue(async()=>{const next=clone(story);next.scenes[sceneId].images=[asset.id];await commit(next);});assets=[asset];}if(!assets.length)throw new Error('还没有生成图片。');check(expected);
        picture?.close();activePictureId=sceneId;picture=createPictureView({scene,assets,
            onListCandidates:async(name,asset,options)=>{check(expected);const tools=await getTools(),old=asset.scene_snapshot.actors.find(a=>a.person===name)?.person_snapshot;if(!old)throw new Error('请选择本图人物。');const text=getContext().chat.slice(0,asset.scene_snapshot.message_id+1).map(m=>proseOf(m.mes)).join('\n').slice(-16000);return listActorCandidates(old,{catalog:tools.catalog,state:story.cast,text,...options});},
            onDeleteCandidate:id=>setCatalogDeleted(id,true),
            onChooseCandidate:async(name,asset,id,options)=>{check(expected);const tools=await getTools();const text=getContext().chat.slice(0,asset.scene_snapshot.message_id+1).map(m=>proseOf(m.mes)).join('\n').slice(-16000);const next=rerollActor(asset.scene_snapshot,name,{...tools,state:story.cast,candidateId:id,text,...options});await revise(next);picture?.close();},
            onReroll:async(name,asset)=>{check(expected);const tools=await getTools();const next=rerollActor(asset.scene_snapshot,name,{...tools,state:story.cast});await revise(next);picture?.close();},
            onRedraw:async(asset,{interactionView='auto',partnerVisibility}={})=>{check(expected);manual?.close();const source=clone(asset.scene_snapshot);delete source.confirmed_prompt;const original=focusFrame(source,{interactionView,partnerVisibility});original.confirmed_prompt=compileScene(original,frameState(original));applyArtistPreference(original);
                for(const actor of original.actors){const current=Object.values(story.cast.people).find(p=>p.person===actor.person);if(sameAppearance(current,actor.person_snapshot)){actor.person_snapshot.reference_enabled=usesImageReference(current);if(usesImageReference(current)&&current.reference_ids?.length)actor.person_snapshot.reference_ids=clone(current.reference_ids);}}
                picture?.close();const epoch=++turn;manual=createManualView({onPrepare:async(correction='')=>{
                check(expected);abort=new AbortController();const current_people=original.actors.map(a=>({person:a.person,appearance:a.person_snapshot.chosen_appearance_tags,face_description:a.person_snapshot.face_description||'',current_outfit:outfitText(a.outfit),outfit:a.outfit}));
                const value=await requestManualFlash({scene:(original.excerpt||original.summary).slice(0,6000),story:'',current_people,wardrobe_schema:2,correction},{fetcher,requester:manualRequester,signal:abort.signal});check(expected);if(epoch!==turn)throw new Error('窗口已关闭。');
                if(!value.scene_composition||!Array.isArray(value.people))throw new Error('本图人物抽取不完整，原 tags 已保留。');value.people=value.people.filter(p=>original.actors.some(a=>a.person===p.person));if(value.people.length!==original.actors.length)throw new Error('本图人物抽取不完整，原 tags 已保留。');const changed=clone(original);changed.composition=value.scene_composition;changed.summary=value.summary;if(value.interactions?.length)changed.interactions=value.interactions;
                for(const a of changed.actors){const update=value.people.find(p=>p.person===a.person);if(!update)throw new Error('重新整理不能替换本图人物。');a.action_prompt=update.action_prompt;a.outfit=applyOutfit(a.outfit,update.outfit);a.wardrobe={description:outfitText(a.outfit),tags:[]};}
                delete changed.confirmed_prompt;const focused=focusFrame(changed,{interactionView,partnerVisibility});focused.confirmed_prompt=compileScene(focused,frameState(focused));applyArtistPreference(focused);return {scene:focused};
            },onConfirm:async result=>{if(epoch!==turn)throw new Error('窗口已关闭。');check(expected);await revise(result.scene);},onClose:()=>{abort?.abort();turn++;}});manual.open({excerpt:original.excerpt||original.summary},{scene:original});},
            onSave:async(name,asset)=>{check(expected);const current=Object.values(story.cast.people).find(p=>p.person===name);let referenceEnabled=usesImageReference(current);const data=await chooseReference(asset,name,{multiple:asset.scene_snapshot.actors.length>1,referenceEnabled,onPreference:value=>{referenceEnabled=value;}});if(!data)return;check(expected);const actor=asset.scene_snapshot.actors.find(a=>a.person===name);const reference=await saveAsset(data,asset.scene_snapshot);await enqueue(async()=>{check(expected);const next=clone(story),key=Object.entries(next.cast.people).find(([,p])=>p.person===name)?.[0];if(!key)throw new Error('人物档案不存在。');const p=clone(actor.person_snapshot);p.version=(next.cast.people[key].version||0)+1;p.accepted=true;p.reference_enabled=referenceEnabled;p.reference_ids=[reference.id,...(sameAppearance(p,next.cast.people[key])?next.cast.people[key].reference_ids||[]:[])].filter((id,i,ids)=>ids.indexOf(id)===i).slice(0,4);p.saved_from=asset.id;next.cast.people[key]=p;refreshPendingPerson(next,name,p);await commit(next);});notify(name+' 的固定形象已保存。'+(referenceEnabled?'后续新图会用保存图片辅助绘制。':'后续新图复用固定人物 tags，图片保留在人物档案中。'));},
            onDelete:async asset=>{check(expected);const next=clone(story.scenes[sceneId]);next.images=next.images.filter(id=>id!==asset.id);next.archived_images=(next.archived_images||[]).filter(id=>id!==asset.id);next.selected_image=next.images.at(-1);next.hide_images=!next.images.length;await revise(next,{draw:false,images:next.images});},onSelect:async asset=>{check(expected);await enqueue(async()=>{const next=clone(story);next.scenes[sceneId].selected_image=asset.id;await commit(next);});}});
    }
    function mediaScene(img){const span=img.closest('span[data-request-id]');const button=span?.previousElementSibling;const marker=button?.dataset?.link||button?.getAttribute('data-link')||'';try{return readControl(marker,'ADSCENE')?.value.id;}catch{return null;}}
    let openingPicture='',activePictureId='';
    const managedOpen=img=>{const id=mediaScene(img);if(!id||!story?.scenes[id])return false;if(openingPicture===id||activePictureId===id&&picture?.isOpen())return true;openingPicture=id;selection?.close();openPicture(id,img.src).catch(error=>notify(error.message,'error')).finally(()=>{if(openingPicture===id)openingPicture='';});return true;};
    const double=e=>{const img=e.target.closest?.('#chat img');if(!img||!managedOpen(img))return;e.preventDefault();e.stopImmediatePropagation();};
    const refreshQueue=createDomRefresh(mountNow,{schedule:cb=>typeof requestAnimationFrame==='function'?requestAnimationFrame(cb):cb()});
    const assetReads=new Map(),imageReads=new WeakMap();
    function mount(rows){refreshQueue.request(rows);}
    function mountNow(changed){const ctx=getContext(),rows=changed||[...document.querySelectorAll('#chat .mes[mesid]')];for(const row of rows){if(row.isConnected===false)continue;const id=Number(row.getAttribute('mesid'));if(ctx.chat[id]?.is_user||row.querySelector('.ad2-select'))continue;const b=document.createElement('button');b.className='ad2-select';b.type='button';b.textContent='选段生图';b.addEventListener('pointerdown',e=>e.preventDefault());b.onclick=()=>{try{const s=snapshotSelection()||selection?.getSnapshot();if(s&&s.messageId===id){openManual(s).catch(error=>notify(error.message,'error'));return;}const message=ctx.chat[id];if(!message||!story)throw new Error('人物库仍在加载，请稍后重试。');selection?.close();paragraphPicker?.close();paragraphPicker=openParagraphPicker({chatKey:key(),messageId:id,swipeId:message.swipe_id??0,raw:String(message.mes)},{onChoose:s=>openManual(s).catch(error=>notify(error.message,'error'))});}catch(error){notify(error.message,'warning');}};(row.querySelector('.mes_buttons')||row).append(b);}
        for(const row of rows){if(row.isConnected===false)continue;for(const span of row.querySelectorAll('span[data-request-id]')){const marker=span.previousElementSibling?.dataset?.link;if(!marker)continue;let id;try{id=readControl(marker,'ADSCENE')?.value.id;}catch{continue;}const s=story?.scenes[id];if(!s)continue;if(s.hide_images&&!s.images?.length){for(const img of span.querySelectorAll('img'))img.remove();continue;}if(s.images?.length&&!span.querySelector('img')){const img=document.createElement('img');img.className='ad-owned-image';img.alt='已保存的剧情图片';span.append(img);}else if(span.querySelectorAll('img').length>1)span.querySelector('img.ad-owned-image')?.remove();}}
        const expected=activeKey;for(const row of rows){if(row.isConnected===false)continue;for(const img of row.querySelectorAll('img')){const id=mediaScene(img),selected=story?.scenes[id]?.selected_image||story?.scenes[id]?.images?.at(-1),pending=imageReads.get(img);if(!selected||img.dataset.adSelected===selected||pending?.selected===selected&&pending.expected===expected)continue;
            let read=assetReads.get(selected);if(!read){read=Promise.resolve().then(()=>library.getAsset(selected));assetReads.set(selected,read);read.finally(()=>{if(assetReads.get(selected)===read)assetReads.delete(selected);}).catch(()=>{});}
            const token={selected,expected};imageReads.set(img,token);read.then(asset=>{if(imageReads.get(img)===token&&img.isConnected!==false&&key()===expected&&activeKey===expected&&(story?.scenes[id]?.selected_image||story?.scenes[id]?.images?.at(-1))===selected&&asset){img.src=asset.data;img.dataset.adSelected=selected;}}).catch(()=>{}).finally(()=>{if(imageReads.get(img)===token)imageReads.delete(img);});
        }}}
    function bind(){selection=installSelectionMenu({getSnapshot:snapshotSelection,onGenerate:s=>openManual(s).catch(error=>notify(error.message,'error')),notify});document.addEventListener('dblclick',double,true);window.addEventListener('animadex-managed-image-open',e=>{if(e.detail?.media)managedOpen(e.detail.media);});const chat=document.querySelector('#chat');if(chat)new MutationObserver(records=>mount(changedChatRows(records,chat))).observe(chat,{childList:true,subtree:true});mount();}
    function cancel(){turn++;renderQueue.cancelQueued('聊天、正文或操作已变化');abort?.abort();manual?.close();picture?.close();selection?.close();paragraphPicker?.close();}
    async function checkConnections(){const checks=[];try{const info=manualConnection(getContext(),setting());checks.push({kind:'manual',ok:true,text:info.kind==='native'?'选段接口已配置：'+info.name+' · '+info.model+'（尚未发起模型请求）':'选段使用电脑助手（尚未检测联网）'});}catch(error){checks.push({kind:'manual',ok:false,text:error.message});}try{const config=inspectRenderConfig(getContext().extensionSettings['st-chatu8']),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetcher(config.url+'/system_stats',{signal:controller.signal});if(!response.ok)throw new Error('ComfyUI 检测失败：HTTP '+response.status);const stats=await response.json();if(!stats.system&&!Array.isArray(stats.devices))throw new Error('接口返回的不是 ComfyUI 状态');checks.push({kind:'render',ok:true,text:'ComfyUI 可连接 · '+config.workflow+' · '+config.nodes+' 个节点；实际生图仍可能遇到模型或节点错误'});}finally{clearTimeout(timer);}}catch(error){checks.push({kind:'render',ok:false,text:error.name==='AbortError'?'ComfyUI 检测超时，请检查手机能否访问绘图地址':error.message});}return checks;}
    const process=id=>async options=>{try{return await processMessage(id,options);}catch(error){autoStatus('invalid','自动插图未准备：'+error.message,id);throw error;}};
    async function updatePerson(name,patch){return enqueue(async()=>{const next=clone(story),entry=Object.entries(next.cast.people).find(([,p])=>p.person===name);if(!entry)throw new Error('人物不存在。');const p=entry[1];
        if(patch.tags!==undefined){if(!Array.isArray(patch.tags)||patch.tags.some(t=>typeof t!=='string'||/[;{}@$<>]/.test(t)))throw new Error('固定外貌标签格式错误。');const tags=[...new Set(patch.tags)];if(JSON.stringify(tags)!==JSON.stringify(p.chosen_appearance_tags||[])){p.chosen_appearance_tags=tags;p.exact_id=false;}}
        for(const[field,limit]of[['age_description',120],['face_description',700]])if(patch[field]!==undefined){if(typeof patch[field]!=='string'||patch[field].length>limit||/[;{}@$<>]/.test(patch[field]))throw new Error('人物描述格式错误。');if(field==='face_description'&&patch[field].trim()!==p[field])p.face_explicit=true;p[field]=patch[field].trim();}
        for(const field of['trigger_enabled','reference_enabled'])if(patch[field]!==undefined){if(typeof patch[field]!=='boolean')throw new Error('形象使用选项必须是开关。');p[field]=patch[field];if(field==='trigger_enabled')p.trigger_source='user';}
        if(patch.style!==undefined){if(!['model_default','painterly','mikko','bluearchive','rdbt','pc98'].includes(patch.style))throw new Error('画风不存在。');p.style=patch.style;p.style_chosen=true;p.style_explicit=true;}
        if(patch.artist_tags!==undefined)p.artist_tags=artistTags(patch.artist_tags);
        if(patch.prototype_trigger!==undefined){if(typeof patch.prototype_trigger!=='string'||patch.prototype_trigger.length>1200||/[;{}@$<>\x00-\x1f]/.test(patch.prototype_trigger))throw new Error('原型识别词格式无效。');p.prototype_trigger=patch.prototype_trigger.trim();}
        if(patch.aliases!==undefined){if(!Array.isArray(patch.aliases)||patch.aliases.length>12||patch.aliases.some(v=>typeof v!=='string'||!v.trim()||v.length>120||/[;{}@$<>]/.test(v)))throw new Error('人物别名格式无效。');const aliases=[...new Set(patch.aliases.map(v=>v.trim()))];for(const alias of aliases){const match=findPerson(next.cast.people,alias);if(match&&match[1]!==p)throw new Error('别名 '+alias+' 已属于 '+match[1].person+'，请先明确对应关系。');}p.aliases=aliases;}
        if(patch.referenceData){const fake={id:'profile_'+name,revision:1,composition:'character reference',style:p.style,actors:[{person:name,person_snapshot:p,wardrobe:{description:'',tags:[]},action_prompt:'standing'}]};const asset=await saveAsset(patch.referenceData,fake);p.reference_ids=[...new Set([...(p.reference_ids||[]),asset.id])].slice(-4);p.accepted=true;}
        if(patch.removeReference)p.reference_ids=(p.reference_ids||[]).filter(id=>id!==patch.removeReference);
        if(patch.tags!==undefined||patch.age_description!==undefined){const tools=await getTools();reconcileStoryAppearance(p,{catalog:tools.catalog,manual:true});}
        p.version=(p.version||1)+1;refreshPendingPerson(next,name,p);await commit(next);});}
    const getOutfitEvents=()=>Object.fromEntries(Object.entries(story?.events||{}).filter(([,event])=>{const m=getContext().chat[event.message_id];return m&&event.swipe_id===(m.swipe_id??0)&&event.source_hash===sourceHash(m.mes||'');}));
    async function updateOutfit({eventId,person,items}){return enqueue(async()=>{const next=clone(story),event=getOutfitEvents()[eventId];if(!event)throw new Error('此衣装记录所属正文或回复分支已改变，请查看当前分支。');const actor=next.events[eventId].people.find(p=>p.name===person);if(!actor)throw new Error('这个时刻没有该人物的衣装记录。');const outfit=applyOutfit(undefined,{mode:'snapshot',items});actor.outfit={mode:'snapshot',items:outfit.items};for(const scene of Object.values(next.scenes)){if(!scene.automatic||scene.images?.length||[...jobs.values()].some(j=>j.scene.id===scene.id)||scene.message_id<event.message_id||(scene.message_id===event.message_id&&(scene.prose_offset??scene.start)<event.offset))continue;const outfits=priorOutfitsFor(next,{messageId:scene.message_id,swipeId:scene.swipe_id,offset:scene.start,proseOffset:scene.prose_offset,chat:getContext().chat});for(const a of scene.actors)if(a.person===person&&outfits[person]){a.outfit=clone(outfits[person]);a.wardrobe={description:outfitText(a.outfit),tags:[]};delete scene.confirmed_prompt;scene.confirmed_prompt=compileScene(scene,frameState(scene));}}await commit(next);});}
    return {...workflows,load,bind,bridge,returned:async data=>{if(handlingResponses.has(data.id)||!jobs.has(data.id)&&!responses.has(data.id))return;handlingResponses.add(data.id);const completion=responses.get(data.id);try{if(!data.success)throw new Error(data.error||'未收到图片');await returned(data);completion?.resolve();}catch(error){jobs.delete(data.id);completion?.reject(error);notify((data.success?'图片已生成，但保存记录失败：':'绘图未完成：')+error.message,'error');}finally{handlingResponses.delete(data.id);taskChanged();}},processLatest:options=>enqueue(()=>process(getContext().chat.length-1)(options)),processMessage:(id,options)=>enqueue(()=>process(id)(options)),cancel,refresh:mount,updatePerson,updateOutfit,getOutfitEvents,
        beginGeneration,getGenerationStatus:()=>({automatic:clone(automaticStatus),paused:renderQueue.isPaused(),tasks:renderQueue.snapshot().filter(t=>t.chat_key===activeKey),active:jobs.size}),stopQueued:()=>renderQueue.cancelQueued(),resumeQueue:()=>renderQueue.resume(),retryTask:id=>renderQueue.retry(id),checkConnections,
        getManualConnection:()=>{const {profile,...publicInfo}=manualConnection(getContext(),setting());return publicInfo;},getRefreshStats:refreshQueue.stats,getManualProfiles:()=>Object.keys(getContext().extensionSettings['st-chatu8']?.llm_profiles||{}),getStory:()=>clone(story),library,openPicture,openManual,generate,revise,anchors,browseCatalog,catalogFacets,setCatalogDeleted,tryCatalogPerson,getDrawingPreferences:drawingPreferences,saveArtistPreset,importArtists,setDefaultArtist,deleteArtistPreset,exportArtists:()=>({format:ARTIST_FORMAT,version:1,artists:clone(setting().artist_presets||[])}),exportCatalogChoices:()=>({format:'animadex-catalog-choices-v1',version:1,deletedIds:clone(setting().catalog_excluded_ids||[])}),importCatalogChoices,exportLibrary:()=>library.export(),importLibrary:data=>enqueue(async()=>{cancel();await library.import(data);await load();})};
}
