import test from 'node:test';
import assert from 'node:assert/strict';
import {createRenderQueue} from './render-queue.mjs';
import {createStoryApp} from './story-app.mjs';
import {paragraphChoices} from './paragraph-picker.mjs';
import {generationRecipe,recipeDescription,extractArtistTags} from './generation-recipe.mjs';
import {inspectRenderConfig} from './generation-health.mjs';
const pause=()=>new Promise(r=>setImmediate(r));
async function until(condition){for(let i=0;i<100;i++){if(condition())return;await pause();}assert(condition(),'condition did not settle');}
const task=(id='one')=>({id,token:id,key:'chat',scene:{id,message_id:1,summary:'图书馆',revision:1}});
test('render queue waits for output completion before starting another image',async()=>{const pending=[],started=[],q=createRenderQueue({run:t=>new Promise(r=>{started.push(t.id);pending.push(r);})});q.add(task());q.add(task('two'));await pause();assert.deepEqual(started,['one']);assert.equal(q.snapshot()[1].status,'queued');pending.shift()();await pause();assert.deepEqual(started,['one','two']);pending.shift()();await until(()=>q.snapshot().every(t=>t.status==='complete'));});
test('one failed render pauses all pending work and retry is explicit',async()=>{let fail=true,calls=0;const q=createRenderQueue({run:async()=>{calls++;if(fail)throw Error('HTTP 429');}});q.add(task());q.add(task('two'));await until(()=>q.isPaused());assert.equal(calls,1);assert.equal(q.snapshot()[1].status,'queued');fail=false;q.retry('one');await until(()=>q.snapshot().every(t=>t.status==='complete'));assert.equal(calls,3);});
test('cancel and stale source never launch their queued tasks',async()=>{const started=[],wait=[];let valid=true;const q=createRenderQueue({valid:t=>t.id==='one'||valid,run:t=>new Promise(r=>{started.push(t.id);wait.push(r);})});q.add(task());q.add(task('two'));q.add(task('three'));await pause();q.cancelQueued('停止',t=>t.id==='three');valid=false;wait.shift()();await until(()=>q.snapshot()[1].status==='cancelled');assert.deepEqual(started,['one']);assert.equal(q.snapshot()[2].reason,'停止');});
test('queue deduplicates automatic tokens and bounds pending work',async()=>{const wait=[],q=createRenderQueue({maxPending:1,run:()=>new Promise(r=>wait.push(r))});assert(q.add(task()));assert.equal(q.add(task()),false);assert.throws(()=>q.add(task('two')),/队列已满/);await pause();wait.shift()();await until(()=>q.snapshot()[0].status==='complete');});
const capture=()=> 'image###ADCAP'+JSON.stringify({v:2,summary:'图书馆窗边',scene:'library, window, sunlight',people:[]})+'END;###';
function fixture({max=1,render=true}={}){
 globalThis.window={dispatchEvent(){}};globalThis.document={querySelectorAll:()=>[]};globalThis.CustomEvent=class{};
 const store=new Map(),assets=new Map(),requests=[],settings={enabled:true,automatic:true,automatic_render:render,automatic_max_images:max,default_artist_tags:['@wlop']};
 const ctx={characterId:0,chatId:'owned',chat:[{mes:'初始回复'}],chatMetadata:{},extensionSettings:{'st-chatu8':{mode:'comfyui',workerid:'owned-workflow',worker:JSON.stringify({'1':{class_type:'SaveImage',inputs:{}}}),comfyuiUrl:'http://127.0.0.1:8188',MODEL_NAME:'model-test',api_key:'private-never-save'}},setExtensionPrompt(){},updateMessageBlock(){}};
 const library={async getStory(id){return structuredClone(store.get(id));},async saveStory(v,rev){assert.equal(store.get(v.id)?.revision||0,rev);const value={...structuredClone(v),revision:rev+1};store.set(v.id,value);return structuredClone(value);},async saveAsset(a){assets.set(a.id,structuredClone(a));},async getAsset(id){return structuredClone(assets.get(id));}};
 const app=createStoryApp({getContext:()=>ctx,getTools:async()=>({}),setting:()=>settings,library,persist:async p=>{assert.equal(ctx.chat[p.messageId].mes,p.expectedRaw);ctx.chat[p.messageId].mes=p.nextMessage;},notify(){},fetcher:async()=>Response.json({system:{},devices:[]})});
 ctx.eventSource={async emit(type,request){assert.equal(type,'generate-image-request');await app.bridge(request);requests.push(request);}};
 return {app,ctx,settings,requests,assets,async reply(count=1){ctx.chat.push({mes:Array.from({length:count},(_,i)=>'图书馆的窗边，第 '+i+' 个时刻。\n\n'+capture()).join('\n\n')});await app.processLatest({fresh:true});},async complete(success=true){const r=requests.at(-1);await app.returned({id:r.id,success,error:'HTTP 429',imageData:success?'data:image/png;base64,aQ==':undefined,genParams:{width:704,height:1152,model:'actual-model',seed:r.animadexSeed}});}};
}
test('new assistant reply automatically renders only its configured maximum and duplicate events do not repeat it',async()=>{const f=fixture({max:1});await f.app.load();await f.reply(3);await until(()=>f.requests.length===1);await f.app.processLatest({fresh:true});assert.equal(f.requests.length,1);assert.equal(Object.keys(f.app.getStory().scenes).length,3);await f.complete();await until(()=>f.app.getGenerationStatus().tasks[0].status==='complete');assert.equal(f.assets.size,1);assert.equal(f.app.getGenerationStatus().tasks[0].saved_asset_id,[...f.assets.keys()][0]);});
test('empty upstream reply is explained and never starts a drawing request',async()=>{const f=fixture();await f.app.load();f.ctx.chat.push({mes:''});await f.app.processLatest({fresh:true});assert.equal(f.app.getGenerationStatus().automatic.state,'empty_reply');assert.equal(f.requests.length,0);assert.equal(Object.keys(f.app.getStory().scenes).length,0);});
test('API error text remains untouched and is not treated as drawable narrative',async()=>{const f=fixture();await f.app.load();const raw='[API 错误]\n请求超时';f.ctx.chat.push({mes:raw});await f.app.processLatest({fresh:true});assert.equal(f.app.getGenerationStatus().automatic.state,'reply_error');assert.equal(f.ctx.chat.at(-1).mes,raw);assert.equal(f.requests.length,0);});
test('reload and edited historical messages prepare buttons without automatically rendering',async()=>{const f=fixture();f.ctx.chat[0].mes='原有剧情。'+capture();await f.app.load();await f.app.processLatest({fresh:true});await pause();assert.equal(f.requests.length,0);assert.match(f.app.getGenerationStatus().automatic.reason,/历史/);});
test('a delayed chat-load event after a new reply does not turn that generation into historical work',async()=>{const f=fixture();await f.app.load();f.app.beginGeneration('normal');f.ctx.chat.push({mes:'新回复的图书馆场景。'+capture()});await f.app.load();f.app.beginGeneration('quiet');await f.app.processLatest({fresh:true});await until(()=>f.requests.length===1);await f.complete();await until(()=>f.app.getGenerationStatus().tasks[0].status==='complete');});
test('prepare-only mode preserves the full number of manual buttons',async()=>{const f=fixture({render:false});await f.app.load();await f.reply(3);await pause();assert.equal(f.requests.length,0);assert.equal(Object.keys(f.app.getStory().scenes).length,3);assert.match(f.app.getGenerationStatus().automatic.reason,/仅准备/);});
test('missing and invalid drawing controls report distinct automatic reasons without API calls',async()=>{const f=fixture();await f.app.load();f.ctx.chat.push({mes:'只有普通剧情。'});await f.app.processLatest({fresh:true});assert.equal(f.app.getGenerationStatus().automatic.state,'no_marker');f.ctx.chat.push({mes:'普通剧情。image###ADCAP{"v":1,"people":[]}END;###'});await assert.rejects(()=>f.app.processLatest({fresh:true}));assert.equal(f.app.getGenerationStatus().automatic.state,'invalid');assert.equal(f.requests.length,0);});
test('actual queued output stores final artist, native recipe and reported model without private settings',async()=>{const f=fixture();await f.app.load();await f.reply();await until(()=>f.requests.length===1);await f.complete();const asset=[...f.assets.values()][0];assert.deepEqual(asset.recipe.artist_tags,['@wlop']);assert.equal(asset.recipe.workflow,'owned-workflow');assert.equal(asset.genParams.model,'actual-model');assert.match(recipeDescription(asset.recipe,asset.genParams),/actual-model/);assert(!JSON.stringify(asset).includes('private-never-save'));});
test('switching chats stops waiting work and keeps an already returned image with its original chat',async()=>{const f=fixture({max:2});await f.app.load();await f.reply(2);await until(()=>f.requests.length===1);f.ctx.chatId='other';f.ctx.chat=[{mes:'新的聊天'}];f.app.cancel();await f.app.load();await f.complete();await pause();assert.equal(f.requests.length,1);assert.equal(f.assets.size,1);assert.equal(Object.keys(f.app.getStory().scenes).length,0);});
test('an unsupported reference workflow is rejected before any upload instead of silently dropping the reference',()=>{const native={comfyuiUrl:'http://127.0.0.1:8188',worker:JSON.stringify({'1':{class_type:'SaveImage',inputs:{}}})};assert.throws(()=>inspectRenderConfig(native,{actors:[{person_snapshot:{reference_enabled:true,reference_ids:['owned-asset']}}]}),/不支持人物图片参考/);assert.throws(()=>inspectRenderConfig({...native,mode:'novelai'}),/ComfyUI 模式/);assert.throws(()=>inspectRenderConfig({...native,worker:'{"nodes":[]}'}));});
test('paragraph fallback hides reasoning and markers and locates repeated visible paragraphs separately',()=>{const raw='<think>她站在窗边。</think>\n\n她站在窗边。\n\n'+capture()+'\n\n她站在窗边。\n\n<!--ADMEM{"v":2}END-->\n\n<details><summary>思考</summary>不能选择。</details>';const choices=paragraphChoices(raw);assert.equal(choices.length,2);assert(choices[0].start>raw.indexOf('</think>'));assert(choices[1].start>choices[0].end);for(const c of choices)assert.equal(raw.slice(c.start,c.end),c.text);});
test('generation recipe supports multiword and Chinese artist names while excluding protocol tags',()=>{const recipe=generationRecipe({confirmed_prompt:'Scene Composition: library, @artist one, @画师名, @style:model_default; Character 1 Prompt: 1girl;',actors:[]},{api_key:'private',comfyuiUrl:'https://secret.test'},{});assert.deepEqual(recipe.artist_tags,['@artist one','@画师名']);assert(!JSON.stringify(recipe).includes('private'));assert(!JSON.stringify(recipe).includes('secret.test'));});
test('native flattened prompt separates artist tags from following people and supports line delimiters',()=>{assert.deepEqual(extractArtistTags('library | @misaka 12003-gou | okinami (kancolle), @wlop\n@画师名; @wlop, @style:model_default;'),['@misaka 12003-gou','@wlop','@画师名']);});
test('picture usage reports native prompt artists rather than claiming planned tags were applied',()=>{assert.match(recipeDescription({artist_tags:['@ask']},{resolvedPrompt:'library | @citemer | 1girl'}),/画师标签：@citemer/);assert(!recipeDescription({artist_tags:['@ask']},{resolvedPrompt:'library | 1girl'}).includes('@ask'));assert.match(recipeDescription({artist_tags:['@ask']},{}),/未记录渲染端提示词/);});
test('connection preflight does not call a text model and distinguishes configured API from actual Comfy reachability',async()=>{const f=fixture();f.ctx.extensionSettings['st-chatu8'].llm_profiles={默认:{api_url:'https://example.test/v1',api_key:'private',model:'flash'}};const result=await f.app.checkConnections();assert(result.every(r=>r.ok));assert.match(result[0].text,/尚未发起模型请求/);assert.equal(f.requests.length,0);});
