import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createWorldbookLibrary,worldbookInstruction,filterManagedLore,validateWorldbook,RULE_BOOK} from './worldbook-library.mjs';
import {automaticPrompt} from './automatic-instruction.mjs';
const defaultData=JSON.parse(await fs.readFile(new URL('./worldbook-rules.json',import.meta.url),'utf8'));
function fixture(settings={},disk=new Map()){
    let fail=false;const selected=[];
    const host={names:async()=>[...disk.keys()],load:async n=>structuredClone(disk.get(n)),save:async(n,d)=>{if(fail)throw new Error('disk write failed');disk.set(n,structuredClone(d));},delete:async n=>{if(fail)return false;return disk.delete(n);},select:async(n,b)=>{selected.splice(0,selected.length,...b.filter(x=>x.name===n&&x.mode==='native').map(x=>x.name));}};
    const store=createWorldbookLibrary({setting:()=>settings,host,defaultBook:async()=>defaultData});return {store,settings,disk,selected,setFailure(v){fail=v;}};
}
test('first migration installs the actual protocol and keeps it out of native global injection',async()=>{const f=fixture();await f.store.initialize();assert.equal(f.store.list().active,RULE_BOOK);assert.equal(f.disk.size,1);assert.equal(f.selected.length,0);assert(automaticPrompt(null,f.settings).includes('image###ADCAP'));assert(automaticPrompt(null,f.settings).includes('scene 最多8'));});
test('editing saved entries replaces the hardcoded instruction in the next automatic prompt',async()=>{const f=fixture();await f.store.initialize();const book=f.store.get(RULE_BOOK);book.data.entries={'7':{content:'仅在夜晚输出一张图',disable:false}};await f.store.save(RULE_BOOK,book.data,{expected:JSON.stringify(f.store.get(RULE_BOOK).data)});assert.equal(automaticPrompt(null,f.settings),'仅在夜晚输出一张图');assert.equal(f.disk.get(RULE_BOOK).entries['7'].content,'仅在夜晚输出一张图');await f.store.initialize();assert.equal(automaticPrompt(null,f.settings),'仅在夜晚输出一张图');});
test('disabled and deleted entries disappear without a hidden fallback protocol',async()=>{const f=fixture();await f.store.initialize();const b=f.store.get(RULE_BOOK);for(const e of Object.values(b.data.entries))e.disable=true;await f.store.save(RULE_BOOK,b.data);assert.equal(automaticPrompt(null,f.settings),'');await f.store.delete(RULE_BOOK);assert.equal(automaticPrompt(null,f.settings),'');await f.store.initialize();assert.equal(f.disk.size,0);assert.equal(f.store.list().books.length,0);});
test('native editor changes are refreshed before generation and never overwritten on restart',async()=>{const f=fixture();await f.store.initialize();f.disk.get(RULE_BOOK).entries['0'].content='用户在原生编辑器的修改';await f.store.refresh();assert(automaticPrompt(null,f.settings).includes('用户在原生编辑器的修改'));const b=f.store.get(RULE_BOOK);b.data.entries['0'].content='更新事件';f.store.accept(RULE_BOOK,b.data);assert(automaticPrompt(null,f.settings).includes('更新事件'));});
test('deletion in the native editor is respected, including after restart',async()=>{const f=fixture();await f.store.initialize();f.disk.delete(RULE_BOOK);await f.store.refresh();assert.equal(automaticPrompt(null,f.settings),'');await f.store.initialize();assert.equal(f.disk.size,0);});
test('imports roundtrip every unknown field and never overwrite an existing original',async()=>{const data={extensions:{custom:['keep',9]},entries:{'51':{uid:51,comment:'自定义',content:'A',key:['雨'],keysecondary:['风'],sticky:12,position:7,unknown:{a:[1,2]}}}},f=fixture();f.disk.set('原版',data);await f.store.initialize();const imported=await f.store.import(data,{name:'原版',activate:false});assert.equal(imported.name,'原版 (2)');assert.deepEqual(await f.store.export(imported.name),data);assert.deepEqual(f.disk.get('原版'),data);assert.equal(f.store.list().active,RULE_BOOK);});
test('existing worldbook copy leaves the original file unchanged and inactive',async()=>{const f=fixture();const data={entries:{'0':{content:'原稿'}}};f.disk.set('我的原版',data);await f.store.initialize();const copied=await f.store.copyExisting('我的原版');assert.equal(f.store.get(copied.name).mode,'native');assert.deepEqual(f.disk.get('我的原版'),data);assert.equal(f.store.list().active,RULE_BOOK);});
test('invalid imports, save failures and failed deletions retain previously saved state',async()=>{const f=fixture();await f.store.initialize();const before=JSON.stringify(f.store.list());await assert.rejects(f.store.import({entries:{'0':{content:9}}}));assert.equal(JSON.stringify(f.store.list()),before);f.setFailure(true);const data=f.store.get(RULE_BOOK).data;data.entries['0'].content='not saved';await assert.rejects(f.store.save(RULE_BOOK,data));assert.equal(JSON.stringify(f.store.list()),before);await assert.rejects(f.store.delete(RULE_BOOK));assert.equal(JSON.stringify(f.store.list()),before);});
test('concurrent native edits produce a conflict instead of being silently overwritten',async()=>{const f=fixture();await f.store.initialize();const old=f.store.get(RULE_BOOK).data,expected=JSON.stringify(old);f.disk.get(RULE_BOOK).entries['0'].content='别处的新修改';old.entries['0'].content='过期草稿';await assert.rejects(f.store.save(RULE_BOOK,old,{expected}),/别处修改/);assert.equal(f.disk.get(RULE_BOOK).entries['0'].content,'别处的新修改');});
test('native mode uses native activation and sends only dynamic facts through plugin anchors',async()=>{const f=fixture();await f.store.initialize();const r=await f.store.import({entries:{'0':{content:'native keyword rule',key:['雨']}}},{name:'雨天'});assert.deepEqual(f.selected,[r.name]);assert.equal(worldbookInstruction(f.settings),'');assert(!automaticPrompt(null,f.settings).includes('ADCAP'));assert(automaticPrompt({cast:{people:{a:{person:'小陈',aliases:[]}}}},f.settings).includes('小陈'));await f.store.use(null);assert.deepEqual(f.selected,[]);assert.equal(automaticPrompt(null,f.settings),'');});
test('worldbook filter prevents duplicate always-injected rules in all four native lore lists',()=>{const s={worldbook_library:{active:'A',books:[{name:'A',mode:'always'},{name:'B',mode:'native'}]}},rows={globalLore:[{world:'A'},{world:'B'},{world:'C'}],chatLore:[{world:'A'}],personaLore:[{world:'A'}],characterLore:[{world:'A'}]};filterManagedLore(rows,s);assert.deepEqual(rows.globalLore,[{world:'C'}]);assert.equal(rows.chatLore.length+rows.characterLore.length+rows.personaLore.length,0);s.worldbook_library.active='B';rows.globalLore=[{world:'B'}];filterManagedLore(rows,s);assert.equal(rows.globalLore.length,1);s.automatic=false;filterManagedLore(rows,s);assert.equal(rows.globalLore.length,0);});
test('restoring defaults creates a distinct copy, preserving user edits',async()=>{const f=fixture();await f.store.initialize();const d=f.store.get(RULE_BOOK).data;d.entries['0'].content='私人修改';await f.store.save(RULE_BOOK,d);const restored=await f.store.restoreDefault();assert.equal(restored.name,RULE_BOOK+' (2)');assert.equal(f.disk.get(RULE_BOOK).entries['0'].content,'私人修改');assert.deepEqual(f.disk.get(restored.name),defaultData);});
test('entry text is not truncated and validation does not mutate the supplied object',()=>{const data={entries:{'0':{content:'长'.repeat(50000),key:[]}}};const result=validateWorldbook(data);assert.deepEqual(result,data);result.entries['0'].content='x';assert.equal(data.entries['0'].content.length,50000);assert.throws(()=>validateWorldbook({entries:{'0':{content:'x',key:[3]}}}));});
test('unsafe filenames are rejected and operations serialize instead of losing entries',async()=>{const f=fixture();await f.store.initialize();await assert.rejects(f.store.import({entries:{}},{name:'../x'}));const [a,b]=await Promise.all([f.store.import({entries:{}},{name:'并发',activate:false}),f.store.import({entries:{}},{name:'并发',activate:false})]);assert.equal(a.name,'并发');assert.equal(b.name,'并发 (2)');assert.equal(f.store.list().books.length,3);});
test('a temporary read failure suppresses cached rules and native scanning without losing the chosen book',async()=>{const f=fixture();await f.store.initialize();f.settings.worldbook_read_error=true;assert.equal(automaticPrompt(null,f.settings),'');const chosen=f.store.list().active;await f.store.use(chosen);assert.equal(f.store.list().active,chosen);assert(automaticPrompt(null,f.settings).includes('ADCAP'));});
