import {validateWorldbook} from './worldbook-library.mjs';
const e=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};
const field=(label,input)=>{const l=e('label',undefined,{class:'ad-library-field'});l.append(e('span',label),input);return l;};
const download=(data,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'})),a=e('a');a.href=url;a.download=name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export function mountWorldbookPanel({host,store,notify,preview=()=>''}){
    const root=e('section',undefined,{class:'ad-worldbook','aria-label':'生图世界书管理',role:'region'});
    if(!store){root.append(e('p','世界书管理未连接，请重新加载插件。'));host.append(root);return {refresh(){},destroy(){root.remove();}};}
    let current='',draft=null,expected='',entryId='',dirty=false,jsonError='',busy=false;
    const status=e('p','读取世界书…',{role:'status','aria-live':'polite'}),select=e('select',undefined,{'aria-label':'生图世界书'}),name=e('input',undefined,{'aria-label':'世界书名称',type:'text'}),mode=e('select',undefined,{'aria-label':'世界书注入方式'}),entries=e('select',undefined,{'aria-label':'世界书条目',size:'5'}),title=e('input',undefined,{'aria-label':'条目标题',type:'text'}),content=e('textarea',undefined,{'aria-label':'条目内容',rows:'14',spellcheck:'false'}),enabled=e('input',undefined,{'aria-label':'启用此条目',type:'checkbox'}),constant=e('input',undefined,{'aria-label':'条目常驻',type:'checkbox'}),keys=e('input',undefined,{'aria-label':'条目关键词',type:'text'}),json=e('textarea',undefined,{'aria-label':'完整世界书 JSON',rows:'18',spellcheck:'false'}),effective=e('textarea',undefined,{'aria-label':'实际注入预览',rows:'12',readonly:''}),active=e('p'),file=e('input',undefined,{type:'file',accept:'.json,application/json',hidden:'','aria-label':'导入生图世界书文件'}),existing=e('select',undefined,{'aria-label':'酒馆已有世界书'});
    mode.append(e('option','所有启用条目直接注入（不受世界书预算限制）',{value:'always'}),e('option','按酒馆原生触发规则（关键词、概率、预算等）',{value:'native'}));
    const controls=[];
    const action=(label,fn,attrs={})=>{const b=e('button',label,{type:'button',...attrs});controls.push(b);b.onclick=()=>run(fn);return b;};
    async function run(fn){if(busy)return;busy=true;controls.forEach(b=>b.disabled=true);try{await fn();}catch(error){status.textContent=error.message;status.setAttribute('role','alert');notify?.(error.message,'error');}finally{busy=false;controls.forEach(b=>b.disabled=false);}}
    function confirm(title,text,fn){const d=e('dialog',undefined,{class:'ad-manual','aria-label':title}),body=e('div',undefined,{class:'ad-manual-body'}),footer=e('footer');body.append(e('h2',title),e('p',text));const cancel=e('button','取消',{type:'button'}),yes=e('button','确认',{type:'button',class:'ad-primary'});cancel.onclick=()=>d.close();yes.onclick=async()=>{yes.disabled=true;await run(async()=>{await fn();d.close();});yes.disabled=false;};footer.append(cancel,yes);d.append(body,footer);document.body.append(d);d.onclose=()=>d.remove();d.showModal();}
    const abandon=(fn)=>dirty?confirm('放弃世界书草稿？','有未保存的修改。可取消并先保存或导出草稿。',fn):fn();
    const checked=()=>{if(jsonError)throw new Error('完整 JSON 尚有错误：'+jsonError);if(!draft)throw new Error('请先选择或新建世界书。');return validateWorldbook(draft);};
    function changed(){dirty=true;jsonError='';json.value=JSON.stringify(draft,null,2);status.textContent='尚未保存 · 保存后下一轮回复生效';status.setAttribute('role','status');}
    function entryRows(){entries.replaceChildren();if(!draft)return;for(const[id,v]of Object.entries(draft.entries))entries.append(e('option',(v.disable?'停用 · ':'')+(v.comment||'条目 '+id),{value:id}));if(!Object.hasOwn(draft.entries,entryId))entryId=Object.keys(draft.entries)[0]||'';entries.value=entryId;}
    function entryFields(){const item=draft?.entries[entryId];for(const c of [title,content,enabled,constant,keys])c.disabled=!item;title.value=item?.comment||'';content.value=item?.content||'';enabled.checked=item?!item.disable:false;constant.checked=!!item?.constant;keys.value=(item?.key||[]).join(', ');}
    function list(){const state=store.list();select.replaceChildren(e('option','新世界书 / 未选择',{value:''}),...state.books.map(b=>e('option',b.name+(b.name===state.active?'（正在使用）':''),{value:b.name})));select.value=current;active.textContent=state.active?'正在使用：'+state.active:'未使用生图世界书 · 自动规则注入已停止';effective.value=preview()||'没有直接注入的生图规则。原生触发模式下，实际条目由酒馆扫描后加入请求。';}
    function show(book){const previousEntry=current===book?.name?entryId:'';current=book?.name||'';draft=book?structuredClone(book.data):null;expected=book?JSON.stringify(book.data):'';dirty=false;jsonError='';entryId=previousEntry;name.value=current;mode.value=book?.mode||'always';json.value=draft?JSON.stringify(draft,null,2):'';entryRows();entryFields();list();status.textContent=book?'已读取文件 · '+Object.keys(draft.entries).length+' 条。':'请新建、导入或从酒馆复制世界书。';status.setAttribute('role','status');}
    select.onchange=()=>{const wanted=select.value;select.value=current;run(()=>abandon(()=>show(wanted?store.get(wanted):null)));};
    entries.onchange=()=>{if(jsonError){entries.value=entryId;status.textContent='请先修正完整 JSON。';return;}entryId=entries.value;entryFields();};
    title.oninput=()=>{draft.entries[entryId].comment=title.value;changed();entryRows();};content.oninput=()=>{draft.entries[entryId].content=content.value;changed();};enabled.onchange=()=>{draft.entries[entryId].disable=!enabled.checked;changed();entryRows();};constant.onchange=()=>{draft.entries[entryId].constant=constant.checked;changed();};keys.oninput=()=>{draft.entries[entryId].key=keys.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);changed();};mode.onchange=name.oninput=()=>{dirty=true;status.textContent='尚未保存 · 修改已有书名时请使用「另存为世界书」。';};
    json.oninput=()=>{dirty=true;try{draft=validateWorldbook(JSON.parse(json.value));jsonError='';entryRows();entryFields();status.textContent='JSON 有效 · 尚未保存';}catch(error){jsonError=error.message;status.textContent='JSON 错误：'+jsonError;for(const c of [title,content,enabled,constant,keys])c.disabled=true;}};
    const toolbar=e('div',undefined,{class:'ad-worldbook-actions'});
    async function save(asNew=false){const data=checked();let result;if(!name.value.trim())throw new Error('请填写世界书名称。');if(asNew||!current)result=await store.import(data,{name:name.value,mode:mode.value,activate:!current});else{if(name.value.trim()!==current)throw new Error('修改书名后请点击「另存为世界书」，原文件会保留。');result=await store.save(current,data,{mode:mode.value,expected});}show(store.get(result.name));status.textContent='世界书已保存 · 下一轮回复使用保存内容';}
    toolbar.append(action('新建世界书',()=>abandon(()=>{show({name:'新生图世界书',mode:'always',data:{entries:{}}});current='';expected='';dirty=true;list();})),action('保存世界书',()=>save(),{class:'ad-primary'}),action('另存为世界书',()=>save(true)),action('导入世界书',()=>file.click()),action('导出世界书',()=>{download(checked(),name.value||'生图世界书');status.textContent=dirty?'已导出当前草稿（尚未保存到酒馆）':'已导出完整世界书文件';}),action('使用此世界书',async()=>{if(dirty||!current)throw new Error('请先保存修改，再使用此世界书。');await store.use(current);list();status.textContent='已切换生图世界书 · 下一轮生效';}),action('停用生图世界书',async()=>{await store.use(null);list();status.textContent='已停用自动生图规则；可继续手动选段生图。';}),action('重新读取文件',()=>abandon(async()=>{await store.refresh();show(store.list().books.find(b=>b.name===current)||store.list().books.find(b=>b.name===store.list().active)||null);})),action('恢复默认规则副本',()=>abandon(async()=>{const r=await store.restoreDefault();show(store.get(r.name));})),action('删除世界书',()=>{if(!current)throw new Error('请先选择已保存的世界书。');confirm('删除生图世界书？','将删除「'+current+'」的酒馆文件。建议先导出备份；重启与更新不会自动恢复。',async()=>{await store.delete(current);show(null);});},{class:'ad-danger'}));
    file.onchange=()=>run(async()=>{try{const f=file.files[0];if(!f)return;const data=validateWorldbook(JSON.parse((await f.text()).replace(/^\uFEFF/,'')));await abandon(async()=>{const r=await store.import(data,{name:f.name,mode:'native',activate:false});show(store.get(r.name));status.textContent='已导入副本，保留所有字段；确认注入方式后点击「使用此世界书」。';});}finally{file.value='';}});
    const entryActions=e('div',undefined,{class:'ad-worldbook-actions'});entryActions.append(action('添加条目',()=>{checked();let id=0;while(Object.hasOwn(draft.entries,String(id)))id++;entryId=String(id);draft.entries[entryId]={uid:id,comment:'新规则',content:'',key:[],keysecondary:[],constant:true,disable:false,order:100,position:0,probability:100,useProbability:false};changed();entryRows();entryFields();}),action('删除条目',()=>{checked();if(!draft.entries[entryId])throw new Error('请先选择条目。');confirm('删除世界书条目？','此修改保存后才会写入文件。',()=>{delete draft.entries[entryId];changed();entryRows();entryFields();});},{class:'ad-danger'}));
    const entryEditor=e('div',undefined,{class:'ad-worldbook-editor'}),form=e('div');form.append(field('条目标题',title),field('启用此条目',enabled),field('条目内容',content),field('条目常驻（原生模式）',constant),field('关键词（原生模式，逗号分隔）',keys));entryEditor.append(field('世界书条目',entries),form);
    const advanced=e('details'),actual=e('details'),native=e('details'),nativeActions=e('div',undefined,{class:'ad-worldbook-actions'});advanced.append(e('summary','查看 / 编辑完整 JSON 文件'),e('p','完整保留未知字段。高级触发条件、排序、概率与插入位置可以在 JSON 或酒馆原生编辑器修改。'),json);actual.append(e('summary','查看当前直接注入内容'),e('p','下面包含保存的生图规则与当前聊天的人物、衣装事实。原生触发模式的规则通过酒馆世界书扫描发送。'),effective);
    nativeActions.append(action('刷新酒馆世界书列表',async()=>{existing.replaceChildren(...(await store.available()).map(n=>e('option',n,{value:n})));}),action('打开酒馆原生编辑器',()=>{if(!existing.value)throw new Error('请先选择世界书。');store.open(existing.value);}),action('复制到生图世界书',async()=>{if(!existing.value)throw new Error('请先选择世界书。');await abandon(async()=>{const r=await store.copyExisting(existing.value);show(store.get(r.name));status.textContent='已复制完整世界书；原文件保留，副本尚未启用。';});}));native.append(e('summary','查看酒馆已有世界书（含旧指南与原版书）'),field('酒馆已有世界书',existing),nativeActions);
    root.append(e('h3','生图世界书'),e('p','这里编辑实际生图规则。保存后下一轮采用；无需每次重装。旧「使用指南」只是说明，可取消挂载。默认规则请保留 ADCAP 格式，让回复能转换为生图按钮。'),active,field('选择世界书',select),toolbar,field('世界书名称',name),field('注入方式',mode),e('p','直接注入：发送这本书全部启用条目，忽略关键词等触发条件；原生触发：遵循酒馆完整触发机制，可能受预算限制。导入默认采用原生触发，不会自动覆盖或启用。',{class:'ad-library-muted'}),status,entryActions,entryEditor,advanced,actual,native,file);host.append(root);
    async function refresh(){let error;try{await store.refresh();}catch(e){error=e;}list();if(!dirty){const s=store.list();show(s.books.find(b=>b.name===current)||s.books.find(b=>b.name===s.active)||s.books[0]||null);}existing.replaceChildren(...(await store.available()).map(n=>e('option',n,{value:n})));if(error){status.textContent='文件读取失败；显示上次有效内容，可导出后修复并重新导入：'+error.message;status.setAttribute('role','alert');}}
    const update=()=>{list();if(!dirty&&current){const book=store.list().books.find(b=>b.name===current);show(book||null);}};window.addEventListener('animadex-worldbooks-updated',update);
    return {refresh,destroy(){window.removeEventListener('animadex-worldbooks-updated',update);root.remove();}};
}
